//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@interface SBAppSwitcherOrbGestureSettings : SBUISettings
{
    _Bool _useOrbGesture;
    _Bool _forceDrivesInitialProgress;
    _Bool _playInitialHaptic;
    _Bool _playCommitHaptic;
    _Bool _canPop;
    double _translateProgress;
    double _minTranslation;
    double _maxPopTranslation;
    double _commitToNextAppTranslation;
    double _nextAppPopScale;
    double _orbGestureRegionMax;
    double _panHysteresis;
    double _dismissAnimationMass;
    double _dismissAnimationStiffness;
    double _dismissAnimationDamping;
    double _dismissAnimationEpsilon;
    double _presentAnimationMass;
    double _presentAnimationStiffness;
    double _presentAnimationDamping;
    double _additionalThrowDisplacement;
}

+ (id)settingsControllerModule;
@property double additionalThrowDisplacement; // @synthesize additionalThrowDisplacement=_additionalThrowDisplacement;
@property double presentAnimationDamping; // @synthesize presentAnimationDamping=_presentAnimationDamping;
@property double presentAnimationStiffness; // @synthesize presentAnimationStiffness=_presentAnimationStiffness;
@property double presentAnimationMass; // @synthesize presentAnimationMass=_presentAnimationMass;
@property double dismissAnimationEpsilon; // @synthesize dismissAnimationEpsilon=_dismissAnimationEpsilon;
@property double dismissAnimationDamping; // @synthesize dismissAnimationDamping=_dismissAnimationDamping;
@property double dismissAnimationStiffness; // @synthesize dismissAnimationStiffness=_dismissAnimationStiffness;
@property double dismissAnimationMass; // @synthesize dismissAnimationMass=_dismissAnimationMass;
@property _Bool canPop; // @synthesize canPop=_canPop;
@property _Bool playCommitHaptic; // @synthesize playCommitHaptic=_playCommitHaptic;
@property _Bool playInitialHaptic; // @synthesize playInitialHaptic=_playInitialHaptic;
@property double panHysteresis; // @synthesize panHysteresis=_panHysteresis;
@property _Bool forceDrivesInitialProgress; // @synthesize forceDrivesInitialProgress=_forceDrivesInitialProgress;
@property double orbGestureRegionMax; // @synthesize orbGestureRegionMax=_orbGestureRegionMax;
@property double nextAppPopScale; // @synthesize nextAppPopScale=_nextAppPopScale;
@property double commitToNextAppTranslation; // @synthesize commitToNextAppTranslation=_commitToNextAppTranslation;
@property double maxPopTranslation; // @synthesize maxPopTranslation=_maxPopTranslation;
@property double minTranslation; // @synthesize minTranslation=_minTranslation;
@property double translateProgress; // @synthesize translateProgress=_translateProgress;
@property _Bool useOrbGesture; // @synthesize useOrbGesture=_useOrbGesture;
- (void)setDefaultValues;

@end

