//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"
#import "UIStatusBarManager.h"

@class NSHashTable, NSMutableDictionary, NSMutableOrderedSet, NSMutableSet, NSPointerArray, NSString, SBAppStatusBarSettings;

@interface SBAppStatusBarAssertionManager : NSObject <BSDescriptionProviding, UIStatusBarManager>
{
    NSHashTable *_disableAlphaChangeAssertions;
    NSHashTable *_disableUserInteractionChangeAssertions;
    NSMutableOrderedSet *_windowLevelOverrideReasons;
    NSMutableDictionary *_windowLevelOverrideMap;
    NSPointerArray *_statusBarSettingsAssertionsByLevel[11];
    SBAppStatusBarSettings *_currentStatusBarSettings;
    NSMutableDictionary *_edgeInsetsDictionary;
    NSMutableSet *_activeLayoutLayers;
    NSMutableDictionary *_orientationWindowDictionary;
    double _defaultWindowLevel;
    id <BSInvalidatable> _stateCaptureAssertion;
    _Bool _changingStatusBarStyle;
    _Bool _changingStatusBarAlpha;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (void)_applyEdgeInsetsToStatusBar;
- (void)_updateWindowLevel;
- (void)_setStatusBarValueForPropertyWithAssertions:(id)arg1 setter:(CDUnknownBlockType)arg2;
- (id)_descriptionForPropertyWithAssertions:(id)arg1;
- (void)_evaluateSettingsWithStyleAnimations:(id)arg1;
- (void)_cleanUpAllStatusBarSettingsAssertions;
- (void)_modifiedStatusBarSettingsAssertion:(id)arg1 withAnimationParameters:(id)arg2;
- (void)_modifiedStatusBarSettingsAssertion:(id)arg1;
- (void)_removeStatusBarSettingsAssertion:(id)arg1 withAnimationParameters:(id)arg2;
- (void)_removeStatusBarSettingsAssertion:(id)arg1;
- (void)_addStatusBarSettingsAssertion:(id)arg1 withAnimationParameters:(id)arg2;
- (void)_addStatusBarSettingsAssertion:(id)arg1;
- (void)_removeDisableAppStatusBarUserInteractionChangesAssertion:(id)arg1;
- (void)_addDisableAppStatusBarUserInteractionChangesAssertion:(id)arg1;
- (void)_removeDisableAppStatusBarAlphaChangesAssertion:(id)arg1;
- (void)_addDisableAppStatusBarAlphaChangesAssertion:(id)arg1;
- (_Bool)statusBar:(id)arg1 shouldRequestStyle:(long long)arg2 animationParameters:(id)arg3 forced:(_Bool)arg4;
- (_Bool)statusBar:(id)arg1 shouldRequestStyleAttributes:(id)arg2 animationParameters:(id)arg3 forced:(_Bool)arg4;
- (_Bool)statusBar:(id)arg1 shouldSetAlpha:(double)arg2;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) struct UIEdgeInsets statusBarEdgeInsets;
- (void)setStatusBarEdgeInsets:(struct UIEdgeInsets)arg1 forLayoutLayer:(unsigned long long)arg2;
- (void)removeActiveLayoutLayer:(unsigned long long)arg1;
- (void)addActiveLayoutLayer:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long topmostActiveLayoutLayer;
- (id)orientationWindowForLayoutLayer:(unsigned long long)arg1;
- (_Bool)statusBarOrientationShouldFollowWindow:(id)arg1;
- (void)setOrientationWindow:(id)arg1 forStatusBarLayoutLayer:(unsigned long long)arg2;
- (void)removeWindowLevelOverrideReason:(id)arg1;
- (void)setWindowLevel:(double)arg1 forOverrideReason:(id)arg2;
- (void)setDefaultWindowLevel:(double)arg1;
- (_Bool)isStatusBarUserInteractionEnabled;
- (void)setStatusBarUserInteractionEnabled:(_Bool)arg1;
- (_Bool)isStatusBarHidden;
- (void)_setStatusBarForegroundColorStyleRequest:(id)arg1 animated:(_Bool)arg2 withStyleAnimations:(id)arg3;
- (void)_setStatusBarStyle:(long long)arg1 animated:(_Bool)arg2 withStyleAnimations:(id)arg3;
- (void)_setStatusBarAlpha:(double)arg1 withStyleAnimations:(id)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

