//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@class SBAppSwitcherOrbGestureSettings, SBAppSwitcherWallpaperSettings, SBFluidSwitcherAnimationSettings;

@interface SBAppSwitcherSettings : SBUISettings
{
    long long _simplicityOptions;
    _Bool _useAsynchronousRendering;
    _Bool _gridSwitcherAlignControlCenterTopInLandscape;
    _Bool _gridSwitcherAlignControlCenterTopInPortrait;
    _Bool _useTitleOpacityPrototypeSettings;
    _Bool _simplicityOptionNoSnapshots;
    _Bool _simplicityOptionNoStatusBars;
    _Bool _simplicityOptionNoLabels;
    _Bool _simplicityOptionNoIcons;
    _Bool _simplicityOptionNoBlurs;
    _Bool _simplicityOptionNoShadows;
    _Bool _showFloats;
    long long _switcherStyle;
    SBAppSwitcherOrbGestureSettings *_orbGestureSettings;
    SBAppSwitcherWallpaperSettings *_wallpaperSettings;
    long long _killAffordanceStyle;
    long long _selectionHighlightStyle;
    double _highlightSquishyScale;
    double _highlightDimOpacity;
    double _homeToSwitcherDockRubberBand;
    double _homeToSwitcherDockMaxOffsetBeforeRubberBand;
    double _gridSwipeUpPanTranslationForFullTransition;
    double _gridSwipeUpAppScaleProgressMultiplier;
    double _gridSwipeUpMinimumAppScale;
    double _gridSwitcherPageScale;
    double _gridSwitcherHorizontalInterpageSpacingLandscape;
    double _gridSwitcherVerticalNaturalSpacingLandscape;
    double _gridSwitcherHorizontalInterpageSpacingPortrait;
    double _gridSwitcherVerticalNaturalSpacingPortrait;
    double _gridSwitcherSnapToControlCenterHeightSlop;
    double _aExpLayoutCoeff;
    double _bExpLayoutCoeff;
    double _depthPadding;
    double _titleOpacityACoeff;
    double _titleOpacityBCoeff;
    double _titleOpacityCCoeff;
    double _titleOpacityDCoeff;
    double _cmdTabSwitcherSelectionSquareCornerRadiusRatio;
    SBFluidSwitcherAnimationSettings *_animationSettings;
    double _standardPerCardAdditionalScaleCoefficient;
    double _reduceMotionPerCardAdditionalScaleCoefficient;
}

+ (id)settingsControllerModule;
@property _Bool showFloats; // @synthesize showFloats=_showFloats;
@property _Bool simplicityOptionNoShadows; // @synthesize simplicityOptionNoShadows=_simplicityOptionNoShadows;
@property _Bool simplicityOptionNoBlurs; // @synthesize simplicityOptionNoBlurs=_simplicityOptionNoBlurs;
@property _Bool simplicityOptionNoIcons; // @synthesize simplicityOptionNoIcons=_simplicityOptionNoIcons;
@property _Bool simplicityOptionNoLabels; // @synthesize simplicityOptionNoLabels=_simplicityOptionNoLabels;
@property _Bool simplicityOptionNoStatusBars; // @synthesize simplicityOptionNoStatusBars=_simplicityOptionNoStatusBars;
@property _Bool simplicityOptionNoSnapshots; // @synthesize simplicityOptionNoSnapshots=_simplicityOptionNoSnapshots;
@property(nonatomic) double reduceMotionPerCardAdditionalScaleCoefficient; // @synthesize reduceMotionPerCardAdditionalScaleCoefficient=_reduceMotionPerCardAdditionalScaleCoefficient;
@property(nonatomic) double standardPerCardAdditionalScaleCoefficient; // @synthesize standardPerCardAdditionalScaleCoefficient=_standardPerCardAdditionalScaleCoefficient;
@property(retain, nonatomic) SBFluidSwitcherAnimationSettings *animationSettings; // @synthesize animationSettings=_animationSettings;
@property double cmdTabSwitcherSelectionSquareCornerRadiusRatio; // @synthesize cmdTabSwitcherSelectionSquareCornerRadiusRatio=_cmdTabSwitcherSelectionSquareCornerRadiusRatio;
@property double titleOpacityDCoeff; // @synthesize titleOpacityDCoeff=_titleOpacityDCoeff;
@property double titleOpacityCCoeff; // @synthesize titleOpacityCCoeff=_titleOpacityCCoeff;
@property double titleOpacityBCoeff; // @synthesize titleOpacityBCoeff=_titleOpacityBCoeff;
@property double titleOpacityACoeff; // @synthesize titleOpacityACoeff=_titleOpacityACoeff;
@property _Bool useTitleOpacityPrototypeSettings; // @synthesize useTitleOpacityPrototypeSettings=_useTitleOpacityPrototypeSettings;
@property double depthPadding; // @synthesize depthPadding=_depthPadding;
@property double bExpLayoutCoeff; // @synthesize bExpLayoutCoeff=_bExpLayoutCoeff;
@property double aExpLayoutCoeff; // @synthesize aExpLayoutCoeff=_aExpLayoutCoeff;
@property double gridSwitcherSnapToControlCenterHeightSlop; // @synthesize gridSwitcherSnapToControlCenterHeightSlop=_gridSwitcherSnapToControlCenterHeightSlop;
@property _Bool gridSwitcherAlignControlCenterTopInPortrait; // @synthesize gridSwitcherAlignControlCenterTopInPortrait=_gridSwitcherAlignControlCenterTopInPortrait;
@property double gridSwitcherVerticalNaturalSpacingPortrait; // @synthesize gridSwitcherVerticalNaturalSpacingPortrait=_gridSwitcherVerticalNaturalSpacingPortrait;
@property double gridSwitcherHorizontalInterpageSpacingPortrait; // @synthesize gridSwitcherHorizontalInterpageSpacingPortrait=_gridSwitcherHorizontalInterpageSpacingPortrait;
@property _Bool gridSwitcherAlignControlCenterTopInLandscape; // @synthesize gridSwitcherAlignControlCenterTopInLandscape=_gridSwitcherAlignControlCenterTopInLandscape;
@property double gridSwitcherVerticalNaturalSpacingLandscape; // @synthesize gridSwitcherVerticalNaturalSpacingLandscape=_gridSwitcherVerticalNaturalSpacingLandscape;
@property double gridSwitcherHorizontalInterpageSpacingLandscape; // @synthesize gridSwitcherHorizontalInterpageSpacingLandscape=_gridSwitcherHorizontalInterpageSpacingLandscape;
@property double gridSwitcherPageScale; // @synthesize gridSwitcherPageScale=_gridSwitcherPageScale;
@property double gridSwipeUpMinimumAppScale; // @synthesize gridSwipeUpMinimumAppScale=_gridSwipeUpMinimumAppScale;
@property double gridSwipeUpAppScaleProgressMultiplier; // @synthesize gridSwipeUpAppScaleProgressMultiplier=_gridSwipeUpAppScaleProgressMultiplier;
@property double gridSwipeUpPanTranslationForFullTransition; // @synthesize gridSwipeUpPanTranslationForFullTransition=_gridSwipeUpPanTranslationForFullTransition;
@property double homeToSwitcherDockMaxOffsetBeforeRubberBand; // @synthesize homeToSwitcherDockMaxOffsetBeforeRubberBand=_homeToSwitcherDockMaxOffsetBeforeRubberBand;
@property double homeToSwitcherDockRubberBand; // @synthesize homeToSwitcherDockRubberBand=_homeToSwitcherDockRubberBand;
@property double highlightDimOpacity; // @synthesize highlightDimOpacity=_highlightDimOpacity;
@property double highlightSquishyScale; // @synthesize highlightSquishyScale=_highlightSquishyScale;
@property long long selectionHighlightStyle; // @synthesize selectionHighlightStyle=_selectionHighlightStyle;
@property long long killAffordanceStyle; // @synthesize killAffordanceStyle=_killAffordanceStyle;
@property(retain, nonatomic) SBAppSwitcherWallpaperSettings *wallpaperSettings; // @synthesize wallpaperSettings=_wallpaperSettings;
@property(retain, nonatomic) SBAppSwitcherOrbGestureSettings *orbGestureSettings; // @synthesize orbGestureSettings=_orbGestureSettings;
@property _Bool useAsynchronousRendering; // @synthesize useAsynchronousRendering=_useAsynchronousRendering;
@property long long switcherStyle; // @synthesize switcherStyle=_switcherStyle;
- (void).cxx_destruct;
- (long long)effectiveKillAffordanceStyle;
- (void)setPerCardAdditionalScaleCoefficient:(double)arg1;
@property(readonly, nonatomic) double perCardAdditionalScaleCoefficient;
- (_Bool)shouldSimplifyForOptions:(long long)arg1;
@property long long simplicityOptions; // @dynamic simplicityOptions;
- (id)archiveValueForKey:(id)arg1;
- (void)setDefaultValues;

@end

