//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSwitcherWallpaperPageContentView.h"

#import "SBAppSwitcherPageContentView.h"
#import "SBReusableView.h"

@class NSString, NSUUID, SBAppLayout, SBAppSwitcherSettings, SBAppSwitcherSnapshotCacheEntry, SBAppSwitcherSnapshotImageCache, SBApplication, SBOrientationTransformWrapperView, SBSwitcherSnapshotImageView, UIView;

@interface SBAppSwitcherReusableSnapshotView : SBSwitcherWallpaperPageContentView <SBReusableView, SBAppSwitcherPageContentView>
{
    SBOrientationTransformWrapperView *_firstOrientationWrapper;
    SBOrientationTransformWrapperView *_secondOrientationWrapper;
    UIView *_medusaDividerView;
    SBAppSwitcherSnapshotImageCache *_snapshotCache;
    SBApplication *_firstApplication;
    SBApplication *_secondApplication;
    SBAppSwitcherSettings *_settings;
    long long _firstAppSnapshotUpdatedSequenceID;
    long long _secondAppSnapshotUpdatedSequenceID;
    NSUUID *_requestGeneration;
    _Bool _active;
    SBAppLayout *_appLayout;
    SBSwitcherSnapshotImageView *_firstImageView;
    SBSwitcherSnapshotImageView *_secondImageView;
    SBAppSwitcherSnapshotCacheEntry *_firstSnapshotCacheEntry;
    SBAppSwitcherSnapshotCacheEntry *_secondSnapshotCacheEntry;
}

@property(retain, nonatomic) SBAppSwitcherSnapshotCacheEntry *secondSnapshotCacheEntry; // @synthesize secondSnapshotCacheEntry=_secondSnapshotCacheEntry;
@property(retain, nonatomic) SBAppSwitcherSnapshotCacheEntry *firstSnapshotCacheEntry; // @synthesize firstSnapshotCacheEntry=_firstSnapshotCacheEntry;
@property(retain, nonatomic) SBSwitcherSnapshotImageView *secondImageView; // @synthesize secondImageView=_secondImageView;
@property(retain, nonatomic) SBSwitcherSnapshotImageView *firstImageView; // @synthesize firstImageView=_firstImageView;
@property(retain, nonatomic) NSUUID *requestGeneration; // @synthesize requestGeneration=_requestGeneration;
@property(retain, nonatomic) SBAppLayout *appLayout; // @synthesize appLayout=_appLayout;
- (void).cxx_destruct;
- (void)_updateOrientationWrapperContentOrientations;
- (void)_updateDivider;
- (void)_updateTranslucency;
- (long long)_contentOrientationForSnapshotOrientation:(long long)arg1;
- (void)_requestFreshImages;
- (void)_snapshotChanged:(id)arg1;
- (struct CGRect)_frameInLayoutSpaceForRole:(long long)arg1 inAppLayout:(id)arg2 inOrientation:(long long)arg3;
- (struct CGRect)_snapshotImageFrameForCacheEntry:(id)arg1 correspondingToApplication:(id)arg2;
- (void)_updateCornerRadiusIfNecessaryForSnapshotImageView:(id)arg1 forApplication:(id)arg2 cacheEntry:(id)arg3;
- (void)_configureSnapshotImageView:(id)arg1 forApplication:(id)arg2 cacheEntry:(id)arg3;
- (void)setActive:(_Bool)arg1;
- (void)invalidate;
- (void)prepareForReuse;
- (void)layoutSubviews;
@property(nonatomic) long long orientation;
@property(nonatomic) double cornerRadius;
@property(readonly, copy) NSString *description;
- (id)initWithSnapshotCache:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

