//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView;

@interface SBAppSwitcherSoftOutlineShadowView : UIView
{
    UIView *_clippingView;
    UIImageView *_shadowImageViewTop;
    UIImageView *_shadowImageViewBottom;
    UIImageView *_shadowImageViewLeft;
    UIImageView *_shadowImageViewRight;
    UIView *_shadowImageClippingViewTop;
    UIView *_shadowImageClippingViewBottom;
    UIView *_shadowImageClippingViewLeft;
    UIView *_shadowImageClippingViewRight;
}

+ (struct UIEdgeInsets)_shadowCapInsets;
- (void).cxx_destruct;
- (id)_alphaOnlyImageForMaskImage:(id)arg1;
- (void)layoutSubviews;
@property(nonatomic) struct CGRect clippingFrame;
@property(nonatomic) double clippingCornerRadius;
@property(nonatomic) _Bool shouldClip;
- (id)initWithFrame:(struct CGRect)arg1;

@end

