//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@interface SBAttentionAwarenessSettings : SBUISettings
{
    _Bool _shouldUseAttentionSensor;
    double _sampleInterval;
    double _dimInterval;
    double _sleepInterval;
}

+ (id)settingsControllerModule;
+ (_Bool)attentionSensorSupported;
@property(nonatomic) double sleepInterval; // @synthesize sleepInterval=_sleepInterval;
@property(nonatomic) double dimInterval; // @synthesize dimInterval=_dimInterval;
@property(nonatomic) double sampleInterval; // @synthesize sampleInterval=_sampleInterval;
@property(nonatomic) _Bool shouldUseAttentionSensor; // @synthesize shouldUseAttentionSensor=_shouldUseAttentionSensor;
- (void)setDefaultValues;

@end

