//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBBreadcrumbMetric : NSObject
{
}

- (void)postWasTapped:(_Bool)arg1 dataBuilder:(CDUnknownBlockType)arg2;
- (void)postPresentedWithDataBuilder:(CDUnknownBlockType)arg1;
- (id)init;

@end

