//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBApplicationSceneEntity.h"

@interface SBCarApplicationSceneEntity : SBApplicationSceneEntity
{
}

- (id)carApplicationSceneEntity;
- (_Bool)isCarApplicationSceneEntity;
- (Class)viewControllerClass;
- (id)initWithApplication:(id)arg1 screenController:(id)arg2;
- (id)initWithApplicationSceneHandle:(id)arg1;

@end

