//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SBCoverSheetSystemGestureDelegatePositionProviding.h"

@class NSString, SBCoverSheetPositionView, SBCoverSheetSystemGesturesDelegate, SBCoverSheetTransitionSettings, SBLockScreenSettings, SBScreenEdgePanGestureRecognizer;

@interface SBCoverSheetSlidingViewController : UIViewController <SBCoverSheetSystemGestureDelegatePositionProviding>
{
    UIViewController *_contentViewController;
    id <SBCoverSheetSlidingViewControllerDelegate> _delegate;
    SBScreenEdgePanGestureRecognizer *_dismissGestureRecognizer;
    long long _dismissalSlidingMode;
    long long _dismissalTransformMode;
    SBCoverSheetTransitionSettings *_transitionSettings;
    SBCoverSheetPositionView *_positionView;
    SBScreenEdgePanGestureRecognizer *_presentGestureRecognizer;
    SBCoverSheetSystemGesturesDelegate *_systemGesturesDelegate;
    SBLockScreenSettings *_lockScreenSettings;
    long long _presentGestureState;
    long long _dismissGestureState;
    unsigned long long _pendingAnimationCompletionBlockCount;
    struct CGPoint _initialLocation;
}

@property(nonatomic) unsigned long long pendingAnimationCompletionBlockCount; // @synthesize pendingAnimationCompletionBlockCount=_pendingAnimationCompletionBlockCount;
@property(nonatomic, setter=_logDismissGestureState:) long long dismissGestureState; // @synthesize dismissGestureState=_dismissGestureState;
@property(nonatomic, setter=_logPresentGestureState:) long long presentGestureState; // @synthesize presentGestureState=_presentGestureState;
@property(retain, nonatomic) SBLockScreenSettings *lockScreenSettings; // @synthesize lockScreenSettings=_lockScreenSettings;
@property(nonatomic) struct CGPoint initialLocation; // @synthesize initialLocation=_initialLocation;
@property(retain, nonatomic) SBCoverSheetSystemGesturesDelegate *systemGesturesDelegate; // @synthesize systemGesturesDelegate=_systemGesturesDelegate;
@property(retain, nonatomic) SBScreenEdgePanGestureRecognizer *presentGestureRecognizer; // @synthesize presentGestureRecognizer=_presentGestureRecognizer;
@property(retain, nonatomic) SBCoverSheetPositionView *positionView; // @synthesize positionView=_positionView;
@property(nonatomic) __weak SBCoverSheetTransitionSettings *transitionSettings; // @synthesize transitionSettings=_transitionSettings;
@property(nonatomic) long long dismissalTransformMode; // @synthesize dismissalTransformMode=_dismissalTransformMode;
@property(nonatomic) long long dismissalSlidingMode; // @synthesize dismissalSlidingMode=_dismissalSlidingMode;
@property(retain, nonatomic) SBScreenEdgePanGestureRecognizer *dismissGestureRecognizer; // @synthesize dismissGestureRecognizer=_dismissGestureRecognizer;
@property(nonatomic) __weak id <SBCoverSheetSlidingViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIViewController *contentViewController; // @synthesize contentViewController=_contentViewController;
- (void).cxx_destruct;
- (_Bool)_hasAnyPendingAnimationCompletionBlock;
- (void)_noteAnimationCompletionBlockFired;
- (void)_noteStartingNewAnimation;
- (void)_removeSystemGestureRecognizers;
- (void)_addSystemGestureRecognizers;
- (void)_transitionToViewControllerAppearState:(int)arg1 ifNeeded:(_Bool)arg2 forUserGesture:(_Bool)arg3;
- (void)_transitionToViewControllerAppearState:(int)arg1 forUserGesture:(_Bool)arg2;
- (void)_transitionToViewControllerAppearState:(int)arg1;
- (void)_endTransitionToAppeared:(_Bool)arg1;
- (void)_updateForLocation:(struct CGPoint)arg1;
- (void)_beginTransitionFromAppeared:(_Bool)arg1;
- (_Bool)_shouldEndPresentedForEndingGestureRecognizer:(id)arg1;
- (_Bool)_shouldRubberBandForGestureRecognizer:(id)arg1;
- (struct CGAffineTransform)_transformForLocation:(struct CGPoint)arg1;
- (struct CGPoint)_adjustedTouchLocationForCurrentDismissalMode:(struct CGPoint)arg1;
- (struct CGPoint)_velocityForGesture:(id)arg1;
- (struct CGPoint)_locationForGesture:(id)arg1;
- (void)_cancelTransitionForGesture:(id)arg1;
- (struct CGPoint)_finalLocationForTransitionToPresented:(_Bool)arg1;
- (void)_finishTransitionToPresented:(_Bool)arg1 animated:(_Bool)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)_presentOrDismissGestureEndedWithGestureRecognizer:(id)arg1;
- (void)_presentOrDismissGestureChangedWithGestureRecognizer:(id)arg1;
- (void)_dismissGestureBeganWithGestureRecognizer:(id)arg1;
- (void)_presentGestureBeganWithGestureRecognizer:(id)arg1;
- (void)_handleDismissGesture:(id)arg1;
- (void)_handlePresentGesture:(id)arg1;
- (void)_dismissCoverSheetAnimated:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)_presentCoverSheetAnimated:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (_Bool)isTransitioning;
- (long long)participantState;
- (id)dashBoardIdentifier;
- (_Bool)isBottomMostSlider;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutomaticallyForwardRotationMethods;
- (_Bool)wantsFullScreenLayout;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (_Bool)_isDismissed;
- (_Bool)_isPresented;
- (_Bool)isAnyGestureActivelyRecognized;
- (_Bool)_isTransitioning;
- (_Bool)isDismissGestureActive;
- (void)setPresented:(_Bool)arg1 animated:(_Bool)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)invalidate;
- (void)dealloc;
- (id)initWithContentViewController:(id)arg1 canBePulledDown:(_Bool)arg2 dismissalPreemptingGestureRecognizer:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

