//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBCoverSheetSlidingViewControllerDelegate.h"
#import "SBDashBoardExternalAppearanceProviding.h"
#import "SBDashBoardExternalBehaviorProviding.h"
#import "SBSecureAppViewControllerDelegate.h"
#import "_UISettingsKeyObserver.h"

@class BSEventQueue, CADisplayLink, NSMutableSet, NSSet, NSString, SBAsynchronousRenderingAssertion, SBCoverSheetFlyInSettings, SBCoverSheetIconFlyInAnimator, SBCoverSheetSceneManager, SBCoverSheetSecureAppEnvironmentViewController, SBCoverSheetSlidingViewController, SBCoverSheetTransitionSettings, SBCoverSheetUnlockedEnvironmentHoster, SBDashBoardHostedAppViewController, SBLockScreenSettings, SBLockScreenViewControllerBase, SBMainWorkspace, UIColor, UIImpactFeedbackGenerator, UIWindow, _UILegibilitySettings;

@interface SBCoverSheetPresentationManager : NSObject <SBCoverSheetSlidingViewControllerDelegate, SBDashBoardExternalAppearanceProviding, SBDashBoardExternalBehaviorProviding, SBSecureAppViewControllerDelegate, _UISettingsKeyObserver>
{
    _Bool _hasBeenDismissedSinceScreenOn;
    _Bool _shouldDisplayFakeStatusBar;
    _Bool _dismissingCoverSheet;
    _Bool _centerFollowsFinger;
    _Bool _animateIconsOnPresentationToo;
    UIWindow *_coverSheetWindow;
    UIWindow *_secureAppWindow;
    SBCoverSheetSlidingViewController *_secureAppSlidingViewController;
    long long _participantState;
    long long _scrollingStrategy;
    id <SBCoverSheetPresentationDelegate> _delegate;
    id <SBUILockStateProvider> _uiLockStateProvider;
    id <SBUnlockedEnvironmentWindowsProvider> _windowsProvider;
    SBLockScreenViewControllerBase *_lockScreenViewController;
    SBDashBoardHostedAppViewController *_secureAppViewController;
    SBMainWorkspace *_mainWorkspace;
    NSMutableSet *_coverSheetWindowVisibleReasons;
    SBCoverSheetSlidingViewController *_coverSheetSlidingViewController;
    NSMutableSet *_secureAppWindowVisibleReasons;
    SBCoverSheetSecureAppEnvironmentViewController *_secureAppEnvironmentViewController;
    SBCoverSheetUnlockedEnvironmentHoster *_unlockedEnvironmentHoster;
    SBCoverSheetSceneManager *_sceneManager;
    BSEventQueue *_lockUnlockQueue;
    SBLockScreenSettings *_lockScreenSettings;
    UIImpactFeedbackGenerator *_rubberBandFeedbackGenerator;
    unsigned long long _transitionType;
    SBCoverSheetTransitionSettings *_transitionSettings;
    SBAsynchronousRenderingAssertion *_asynchronousRenderingAssertion;
    SBCoverSheetIconFlyInAnimator *_iconAnimator;
    CADisplayLink *_slomoDisplayLink;
    double _transitionProgress;
    double _iconAnimatorProgressOffset;
    SBCoverSheetFlyInSettings *_flyInSettings;
    double _slomoRate;
    double _iconFlyInTension;
    double _iconFlyInFriction;
    struct CGPoint _touchLocation;
}

+ (id)sharedInstance;
@property(nonatomic) double iconFlyInFriction; // @synthesize iconFlyInFriction=_iconFlyInFriction;
@property(nonatomic) double iconFlyInTension; // @synthesize iconFlyInTension=_iconFlyInTension;
@property(nonatomic) double slomoRate; // @synthesize slomoRate=_slomoRate;
@property(nonatomic) _Bool animateIconsOnPresentationToo; // @synthesize animateIconsOnPresentationToo=_animateIconsOnPresentationToo;
@property(nonatomic) _Bool centerFollowsFinger; // @synthesize centerFollowsFinger=_centerFollowsFinger;
@property(retain, nonatomic) SBCoverSheetFlyInSettings *flyInSettings; // @synthesize flyInSettings=_flyInSettings;
@property(nonatomic) struct CGPoint touchLocation; // @synthesize touchLocation=_touchLocation;
@property(nonatomic) double iconAnimatorProgressOffset; // @synthesize iconAnimatorProgressOffset=_iconAnimatorProgressOffset;
@property(nonatomic) double transitionProgress; // @synthesize transitionProgress=_transitionProgress;
@property(nonatomic) _Bool dismissingCoverSheet; // @synthesize dismissingCoverSheet=_dismissingCoverSheet;
@property(retain, nonatomic) CADisplayLink *slomoDisplayLink; // @synthesize slomoDisplayLink=_slomoDisplayLink;
@property(retain, nonatomic) SBCoverSheetIconFlyInAnimator *iconAnimator; // @synthesize iconAnimator=_iconAnimator;
@property(retain, nonatomic) SBAsynchronousRenderingAssertion *asynchronousRenderingAssertion; // @synthesize asynchronousRenderingAssertion=_asynchronousRenderingAssertion;
@property(nonatomic) _Bool shouldDisplayFakeStatusBar; // @synthesize shouldDisplayFakeStatusBar=_shouldDisplayFakeStatusBar;
@property(nonatomic) __weak SBCoverSheetTransitionSettings *transitionSettings; // @synthesize transitionSettings=_transitionSettings;
@property(nonatomic) unsigned long long transitionType; // @synthesize transitionType=_transitionType;
@property(retain, nonatomic) UIImpactFeedbackGenerator *rubberBandFeedbackGenerator; // @synthesize rubberBandFeedbackGenerator=_rubberBandFeedbackGenerator;
@property(retain, nonatomic) SBLockScreenSettings *lockScreenSettings; // @synthesize lockScreenSettings=_lockScreenSettings;
@property(retain, nonatomic) BSEventQueue *lockUnlockQueue; // @synthesize lockUnlockQueue=_lockUnlockQueue;
@property(retain, nonatomic) SBCoverSheetSceneManager *sceneManager; // @synthesize sceneManager=_sceneManager;
@property(retain, nonatomic) SBCoverSheetUnlockedEnvironmentHoster *unlockedEnvironmentHoster; // @synthesize unlockedEnvironmentHoster=_unlockedEnvironmentHoster;
@property(retain, nonatomic) SBCoverSheetSecureAppEnvironmentViewController *secureAppEnvironmentViewController; // @synthesize secureAppEnvironmentViewController=_secureAppEnvironmentViewController;
@property(retain, nonatomic) NSMutableSet *secureAppWindowVisibleReasons; // @synthesize secureAppWindowVisibleReasons=_secureAppWindowVisibleReasons;
@property(retain, nonatomic) SBCoverSheetSlidingViewController *coverSheetSlidingViewController; // @synthesize coverSheetSlidingViewController=_coverSheetSlidingViewController;
@property(retain, nonatomic) NSMutableSet *coverSheetWindowVisibleReasons; // @synthesize coverSheetWindowVisibleReasons=_coverSheetWindowVisibleReasons;
@property(readonly, nonatomic) _Bool hasBeenDismissedSinceScreenOn; // @synthesize hasBeenDismissedSinceScreenOn=_hasBeenDismissedSinceScreenOn;
@property(retain, nonatomic) SBMainWorkspace *mainWorkspace; // @synthesize mainWorkspace=_mainWorkspace;
@property(retain, nonatomic) SBDashBoardHostedAppViewController *secureAppViewController; // @synthesize secureAppViewController=_secureAppViewController;
@property(retain, nonatomic) SBLockScreenViewControllerBase *lockScreenViewController; // @synthesize lockScreenViewController=_lockScreenViewController;
@property(retain, nonatomic) id <SBUnlockedEnvironmentWindowsProvider> windowsProvider; // @synthesize windowsProvider=_windowsProvider;
@property(retain, nonatomic, setter=setUILockStateProvider:) id <SBUILockStateProvider> uiLockStateProvider; // @synthesize uiLockStateProvider=_uiLockStateProvider;
@property(nonatomic) __weak id <SBCoverSheetPresentationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) long long scrollingStrategy; // @synthesize scrollingStrategy=_scrollingStrategy;
@property(nonatomic) long long participantState; // @synthesize participantState=_participantState;
- (void).cxx_destruct;
- (void)_stopSlomoDisplayLinkIfNeeded;
- (void)_tickSlomoDisplayLink;
- (void)_startSlomoDisplayLinkIfNeeded;
- (void)_cleanupIconAnimator;
- (void)_setTransitionProgress:(double)arg1 iconAnimatorProgressOffset:(double)arg2 touchLocation:(struct CGPoint)arg3 force:(_Bool)arg4 animated:(_Bool)arg5;
- (void)_prepareIconAnimatorForPresenting:(_Bool)arg1;
- (void)_relinquishAsynchronousRenderingAssertion;
- (void)_acquireAsynchronousRenderingAssertion;
- (void)_tellDashBoardOurBehaviorChanged;
- (void)_tellDashBoardOurAppearanceChanged;
- (void)_updateSceneClientSettings;
- (void)_prepareSecureAppWindowForDisplay;
- (void)_prepareCoverSheetWindowForDisplay;
- (void)_setCoverSheet:(_Bool)arg1 windowVisible:(_Bool)arg2 forReason:(id)arg3;
- (void)_setSecureAppWindowVisible:(_Bool)arg1 forReason:(id)arg2;
- (void)_setCoverSheetWindowVisible:(_Bool)arg1 forReason:(id)arg2;
- (void)_enqueueBlock:(CDUnknownBlockType)arg1 withName:(id)arg2;
- (void)_notifyDelegateRequestsUnlock;
- (void)_notifyDelegateDidDismiss;
- (void)_notifyDelegateWillDismiss;
- (void)_notifyDelegateDidPresent;
- (void)_notifyDelegateWillPresent;
- (void)_unlockOrientationIfNeeded;
- (void)_lockOrientationToPortraitIfNeeded;
- (void)noteScreenDidTurnOff;
- (void)_cleanupATransition;
- (void)_prepareForATransition;
- (void)_prepareForTransitionToSecureApp;
- (void)_cleanupDismissalTransition;
- (void)_prepareForDismissalTransition;
- (void)_cleanupRubberBandDismissalTransitionForSlidingViewController:(id)arg1;
- (void)_prepareForRubberBandDismissalTransitionForSlidingViewController:(id)arg1;
- (void)_cleanupRubberBandPresentationTransitionForSlidingViewController:(id)arg1;
- (void)_prepareForRubberBandPresentationTransitionForSlidingViewController:(id)arg1;
- (void)_cleanupARubberBandTransitionForSlidingViewController:(id)arg1;
- (void)_prepareForARubberBandTransitionForSlidingViewController:(id)arg1;
- (void)_cleanupPresentationTransition;
- (void)_prepareForPresentationTransitionForUserGesture:(_Bool)arg1;
- (void)_updateIconsFlyInWithSettings:(id)arg1;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)secureAppViewControllerDidAuthenticate:(id)arg1;
- (void)coverSheetSlidingViewController:(id)arg1 transitionAnimateChangeWithProgress:(double)arg2 coversheetFrame:(struct CGRect)arg3 touchLocation:(struct CGPoint)arg4;
- (_Bool)hasContentUnderCoverSheetSlidingViewController:(id)arg1;
- (void)coverSheetSlidingViewControllerDidPassRubberBandThreshold:(id)arg1;
- (void)coverSheetSlidingViewControllerCleanupDismissalTransition:(id)arg1;
- (void)coverSheetSlidingViewControllerPrepareForDismissalTransition:(id)arg1;
- (void)coverSheetSlidingViewControllerCleanupRubberBandedPresentationTransition:(id)arg1;
- (void)coverSheetSlidingViewControllerPrepareForRubberBandedPresentationTransition:(id)arg1;
- (void)coverSheetSlidingViewControllerCleanupPresentationTransition:(id)arg1;
- (void)coverSheetSlidingViewController:(id)arg1 prepareForPresentationTransitionForUserGesture:(_Bool)arg2;
@property(readonly, nonatomic) long long proximityDetectionMode;
@property(readonly, nonatomic) unsigned long long restrictedCapabilities;
@property(readonly, nonatomic) long long notificationBehavior;
@property(readonly, nonatomic) long long idleTimerDuration;
@property(readonly, nonatomic) long long idleTimerMode;
@property(readonly, nonatomic) long long idleWarnMode;
@property(readonly, nonatomic) UIColor *backgroundColor;
@property(readonly, nonatomic) _UILegibilitySettings *legibilitySettings;
@property(readonly, copy, nonatomic) NSSet *components;
@property(readonly, nonatomic) long long backgroundStyle;
@property(readonly, copy, nonatomic) NSString *appearanceIdentifier;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
- (void)_clearSecureAppViewControllers;
- (void)_prepareSecureAppViewController;
@property(retain, nonatomic) SBCoverSheetSlidingViewController *secureAppSlidingViewController; // @synthesize secureAppSlidingViewController=_secureAppSlidingViewController;
- (id)secureAppSlidingViewControllerIfLoaded;
@property(retain, nonatomic) UIWindow *secureAppWindow; // @synthesize secureAppWindow=_secureAppWindow;
@property(readonly, nonatomic, getter=isCoverSheetHostingAnApp) _Bool coverSheetHostingAnApp;
- (id)coverSheetSlidingViewControllerIfLoaded;
- (id)dashBoardViewController;
@property(retain, nonatomic) UIWindow *coverSheetWindow; // @synthesize coverSheetWindow=_coverSheetWindow;
- (_Bool)isDismissGestureActive;
- (_Bool)isVisible;
- (void)setPasscodeLockVisible:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setCoverSheetPresented:(_Bool)arg1 animated:(_Bool)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

