//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@interface SBCoverSheetFlyInSettings : SBUISettings
{
    _Bool _centerFollowsFinger;
    _Bool _animateIconsOnPresentationToo;
    double _iconsFlyInTension;
    double _iconsFlyInFriction;
    double _slomoRate;
    double _progressExponent;
    double _distanceExponent;
}

+ (id)settingsControllerModule;
@property(nonatomic) double distanceExponent; // @synthesize distanceExponent=_distanceExponent;
@property(nonatomic) double progressExponent; // @synthesize progressExponent=_progressExponent;
@property(nonatomic) double slomoRate; // @synthesize slomoRate=_slomoRate;
@property(nonatomic) double iconsFlyInFriction; // @synthesize iconsFlyInFriction=_iconsFlyInFriction;
@property(nonatomic) double iconsFlyInTension; // @synthesize iconsFlyInTension=_iconsFlyInTension;
@property(nonatomic) _Bool animateIconsOnPresentationToo; // @synthesize animateIconsOnPresentationToo=_animateIconsOnPresentationToo;
@property(nonatomic) _Bool centerFollowsFinger; // @synthesize centerFollowsFinger=_centerFollowsFinger;
- (void)setDefaultValues;

@end

