//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBDisplayLayoutElement, FBSScene, FBScene, NSSet, SBLockScreenViewControllerBase, UIWindow;

@interface SBCoverSheetSceneManager : NSObject
{
    UIWindow *_coverSheetWindow;
    SBLockScreenViewControllerBase *_lockScreenViewController;
    FBDisplayLayoutElement *_displayLayoutElement;
    FBScene *_coverSheetServerScene;
    NSSet *_coverSheetClientSceneOcclusions;
    FBSScene *_coverSheetClientScene;
}

@property(retain, nonatomic) FBSScene *coverSheetClientScene; // @synthesize coverSheetClientScene=_coverSheetClientScene;
@property(retain, nonatomic) NSSet *coverSheetClientSceneOcclusions; // @synthesize coverSheetClientSceneOcclusions=_coverSheetClientSceneOcclusions;
@property(retain, nonatomic) FBScene *coverSheetServerScene; // @synthesize coverSheetServerScene=_coverSheetServerScene;
@property(retain, nonatomic) FBDisplayLayoutElement *displayLayoutElement; // @synthesize displayLayoutElement=_displayLayoutElement;
@property(retain, nonatomic) SBLockScreenViewControllerBase *lockScreenViewController; // @synthesize lockScreenViewController=_lockScreenViewController;
@property(nonatomic) __weak UIWindow *coverSheetWindow; // @synthesize coverSheetWindow=_coverSheetWindow;
- (void).cxx_destruct;
- (void)updateForegroundScenesUnderLock:(_Bool)arg1;
- (void)updateSceneClientSettings;
- (void)setSceneBackgrounded:(_Bool)arg1;
- (void)setDisplayLayoutElementActive:(_Bool)arg1;
- (void)updateSceneManagerForPresented:(_Bool)arg1;
- (id)initWithCoverSheetWindow:(id)arg1 lockScreenViewController:(id)arg2;

@end

