//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBCoverSheetSlidingViewController.h"

@class SBCoverSheetPanelBackgroundContainerView, SBCoverSheetParallaxContainerView, SBFTouchPassThroughView, SBUIBackgroundView, SBWallpaperEffectView;

@interface SBCoverSheetPrimarySlidingViewController : SBCoverSheetSlidingViewController
{
    SBFTouchPassThroughView *_unlockedContentOverlayView;
    SBCoverSheetPanelBackgroundContainerView *_panelBackgroundContainerView;
    SBFTouchPassThroughView *_parallaxClippingView;
    SBCoverSheetParallaxContainerView *_parallaxContainerView;
    SBUIBackgroundView *_panelBlurView;
    SBWallpaperEffectView *_panelWallpaperEffectView;
}

@property(retain, nonatomic) SBWallpaperEffectView *panelWallpaperEffectView; // @synthesize panelWallpaperEffectView=_panelWallpaperEffectView;
@property(retain, nonatomic) SBUIBackgroundView *panelBlurView; // @synthesize panelBlurView=_panelBlurView;
@property(retain, nonatomic) SBCoverSheetParallaxContainerView *parallaxContainerView; // @synthesize parallaxContainerView=_parallaxContainerView;
@property(retain, nonatomic) SBFTouchPassThroughView *parallaxClippingView; // @synthesize parallaxClippingView=_parallaxClippingView;
@property(retain, nonatomic) SBCoverSheetPanelBackgroundContainerView *panelBackgroundContainerView; // @synthesize panelBackgroundContainerView=_panelBackgroundContainerView;
@property(retain, nonatomic) SBFTouchPassThroughView *unlockedContentOverlayView; // @synthesize unlockedContentOverlayView=_unlockedContentOverlayView;
- (void).cxx_destruct;
- (void)_createWallpaperEffectViewFullScreen:(_Bool)arg1;
- (void)_endTransitionToAppeared:(_Bool)arg1;
- (void)_updateForLocation:(struct CGPoint)arg1;
- (void)_beginTransitionFromAppeared:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)loadView;

@end

