//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CCUIModularControlCenterOverlayViewControllerDelegate.h"
#import "SBDashBoardExternalBehaviorProviding.h"
#import "SBDashBoardExternalPresentationProviding.h"
#import "SBGrabberTongueDelegate.h"
#import "SBIdleTimerProviding.h"

@class CCUIModularControlCenterOverlayViewController, FBDisplayLayoutElement, FBUIApplicationSceneDeactivationAssertion, NSArray, NSHashTable, NSString, SBControlCenterSystemAgent, SBControlCenterWindow, SBGrabberTongue;

@interface SBControlCenterController : NSObject <CCUIModularControlCenterOverlayViewControllerDelegate, SBGrabberTongueDelegate, SBDashBoardExternalBehaviorProviding, SBDashBoardExternalPresentationProviding, SBIdleTimerProviding>
{
    id <SBIdleTimerCoordinating> _idleTimerCoordinator;
    SBControlCenterWindow *_window;
    CCUIModularControlCenterOverlayViewController *_viewController;
    SBGrabberTongue *_grabberTongue;
    SBControlCenterSystemAgent *_systemAgent;
    FBUIApplicationSceneDeactivationAssertion *_resignActiveAssertion;
    FBDisplayLayoutElement *_displayLayoutElement;
    NSHashTable *_observers;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreatingIfNeeded:(_Bool)arg1;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) FBDisplayLayoutElement *displayLayoutElement; // @synthesize displayLayoutElement=_displayLayoutElement;
@property(retain, nonatomic) FBUIApplicationSceneDeactivationAssertion *resignActiveAssertion; // @synthesize resignActiveAssertion=_resignActiveAssertion;
@property(retain, nonatomic) SBControlCenterSystemAgent *systemAgent; // @synthesize systemAgent=_systemAgent;
@property(retain, nonatomic) SBGrabberTongue *grabberTongue; // @synthesize grabberTongue=_grabberTongue;
@property(retain, nonatomic) CCUIModularControlCenterOverlayViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) SBControlCenterWindow *window; // @synthesize window=_window;
@property(nonatomic) __weak id <SBIdleTimerCoordinating> idleTimerCoordinator; // @synthesize idleTimerCoordinator=_idleTimerCoordinator;
- (void).cxx_destruct;
- (id)coordinatorRequestedIdleTimerDescriptor:(id)arg1;
@property(readonly, nonatomic) long long proximityDetectionMode;
@property(readonly, nonatomic) long long idleTimerDuration;
@property(readonly, nonatomic) long long idleTimerMode;
@property(readonly, nonatomic) long long idleWarnMode;
@property(readonly, nonatomic) unsigned long long restrictedCapabilities;
@property(readonly, nonatomic) long long notificationBehavior;
@property(readonly, nonatomic) long long scrollingStrategy;
@property(readonly, copy, nonatomic) NSArray *presentationRegions;
@property(readonly, nonatomic) __weak id <UICoordinateSpace> presentationCoordinateSpace;
@property(readonly, nonatomic) long long participantState;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
- (_Bool)_shouldUseControlCenterRevealConfirmation;
- (double)_ambiguousActivationMargin;
- (_Bool)_shouldShowGrabberOnFirstSwipe;
- (_Bool)allowShowTransitionSystemGesture;
- (_Bool)allowShowTransition;
- (struct CGPoint)_presentGestureVelocityInView;
- (struct CGPoint)_presentGestureLocationInView;
- (void)_uiRelockedNotification:(id)arg1;
- (void)_lockStateChangedNotification:(id)arg1;
- (void)_enumerateObservers:(CDUnknownBlockType)arg1;
- (id)_controlCenterWindow;
- (void)_updateWindowVisibility;
- (void)_updateWindowOrientation;
- (void)_didDismiss;
- (void)_willPresent;
- (void)_didEndTransition;
- (void)_willBeginTransition;
- (void)controlCenterViewController:(id)arg1 didChangePresentationState:(unsigned long long)arg2;
- (void)grabberTongueCanceledPulling:(id)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueEndedPulling:(id)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueUpdatedPulling:(id)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueBeganPulling:(id)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueDidDismiss:(id)arg1;
- (void)grabberTongueWillPresent:(id)arg1;
- (double)grabberTongueCenterOnEdge:(id)arg1;
- (double)grabberTongueAmbiguousActivationMargin:(id)arg1;
- (_Bool)grabberTongueRequiredOutsideGrabberFreeRegion:(id)arg1;
- (_Bool)grabberTongueRequiredForWholeEdge:(id)arg1;
- (_Bool)grabberTongueOrPullEnabled:(id)arg1;
- (void)_dismissExpandedModuleWithCompletion:(CDUnknownBlockType)arg1;
- (void)_presentExpandedModuleWithCompletion:(CDUnknownBlockType)arg1;
- (void)dismissAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dismissAnimated:(_Bool)arg1;
- (void)presentAnimated:(_Bool)arg1;
- (_Bool)handleMenuButtonTap;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
@property(readonly, nonatomic, getter=isVisible) _Bool visible;
@property(readonly, nonatomic, getter=isPresented) _Bool presented;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

