//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SBApplicationHosting.h"
#import "SBDashBoardPasscodeViewControllerDelegate.h"

@class NSString, SBDashBoardHostedAppViewController, SBDashBoardPasscodeViewController, UIView;

@interface SBCoverSheetSecureAppEnvironmentViewController : UIViewController <SBDashBoardPasscodeViewControllerDelegate, SBApplicationHosting>
{
    SBDashBoardPasscodeViewController *_passcodeViewController;
    SBDashBoardHostedAppViewController *_secureAppViewController;
    UIView *_maskingView;
}

@property(readonly, nonatomic) UIView *maskingView; // @synthesize maskingView=_maskingView;
@property(readonly, nonatomic) SBDashBoardHostedAppViewController *secureAppViewController; // @synthesize secureAppViewController=_secureAppViewController;
- (void).cxx_destruct;
- (void)hostedAppWillRotateToInterfaceOrientation:(long long)arg1;
- (id)hostedApp;
- (_Bool)isHostingAnApp;
- (_Bool)canHostAnApp;
- (void)passcodeViewControllerDidCancelPasscodeEntry:(id)arg1;
- (void)passcodeViewController:(id)arg1 didCompletePasscodeEntry:(_Bool)arg2;
- (void)passcodeViewControllerDidBeginPasscodeEntry:(id)arg1;
- (void)viewDidLoad;
- (void)setPasscodeLockVisible:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithSecureAppViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

