//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBCoverSheetSlidingViewController;

@protocol SBCoverSheetSlidingViewControllerDelegate <NSObject>
- (void)coverSheetSlidingViewController:(SBCoverSheetSlidingViewController *)arg1 transitionAnimateChangeWithProgress:(double)arg2 coversheetFrame:(struct CGRect)arg3 touchLocation:(struct CGPoint)arg4;
- (_Bool)hasContentUnderCoverSheetSlidingViewController:(SBCoverSheetSlidingViewController *)arg1;
- (void)coverSheetSlidingViewControllerDidPassRubberBandThreshold:(SBCoverSheetSlidingViewController *)arg1;
- (void)coverSheetSlidingViewControllerCleanupRubberBandedPresentationTransition:(SBCoverSheetSlidingViewController *)arg1;
- (void)coverSheetSlidingViewControllerPrepareForRubberBandedPresentationTransition:(SBCoverSheetSlidingViewController *)arg1;
- (void)coverSheetSlidingViewControllerCleanupDismissalTransition:(SBCoverSheetSlidingViewController *)arg1;
- (void)coverSheetSlidingViewControllerPrepareForDismissalTransition:(SBCoverSheetSlidingViewController *)arg1;
- (void)coverSheetSlidingViewControllerCleanupPresentationTransition:(SBCoverSheetSlidingViewController *)arg1;
- (void)coverSheetSlidingViewController:(SBCoverSheetSlidingViewController *)arg1 prepareForPresentationTransitionForUserGesture:(_Bool)arg2;
@end

