//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

@class SBDashBoardTodayViewController, UINavigationController;

@interface SBDashBoardTodayContentViewController : SBDashBoardViewControllerBase
{
    SBDashBoardTodayViewController *_todayViewController;
    UINavigationController *_spotlightNavigationController;
}

@property(retain, nonatomic) UINavigationController *spotlightNavigationController; // @synthesize spotlightNavigationController=_spotlightNavigationController;
@property(retain, nonatomic) SBDashBoardTodayViewController *todayViewController; // @synthesize todayViewController=_todayViewController;
- (void).cxx_destruct;
- (void)aggregateBehavior:(id)arg1;
- (void)aggregateAppearance:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

@end

