//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardPageViewController.h"

#import "SBDashBoardCombinedListViewControllerDelegate.h"
#import "SBDashBoardNotificationDestination.h"
#import "SBDashBoardPageViewControllerProtocol.h"
#import "SBDashBoardStatusTextViewControllerDelegate.h"
#import "SBLockScreenNowPlayingControllerDelegate.h"
#import "_UISettingsKeyObserver.h"

@class NSArray, NSSet, NSString, SBDashBoardAppearance, SBDashBoardBehavior, SBDashBoardCombinedListViewController, SBDashBoardNowPlayingController, SBDashBoardPresentation, SBDashBoardStatusTextViewController, SBDashBoardUserPictureViewController, SBLockScreenLogoutButtonViewController, SBLockScreenSettings, UIColor, _UILegibilitySettings;

@interface SBDashBoardMainPageContentViewController : SBDashBoardPageViewController <SBDashBoardStatusTextViewControllerDelegate, SBLockScreenNowPlayingControllerDelegate, _UISettingsKeyObserver, SBDashBoardCombinedListViewControllerDelegate, SBDashBoardNotificationDestination, SBDashBoardPageViewControllerProtocol>
{
    SBDashBoardNowPlayingController *_nowPlayingController;
    long long _nowPlayingState;
    SBDashBoardUserPictureViewController *_userPictureViewController;
    SBDashBoardCombinedListViewController *_combinedListViewController;
    SBDashBoardStatusTextViewController *_statusTextViewController;
    SBLockScreenLogoutButtonViewController *_logoutButtonViewController;
    SBLockScreenSettings *_testSettings;
    _Bool _authenticatedSinceFingerOn;
    NSString *_cachedMesaFailureText;
    _Bool _temporaryMesaFailureTextActive;
    _Bool _useFakeBlur;
    id <SBCoverSheetSecureAppLaunching> _secureAppLauncher;
}

+ (double)_phoneListWidth;
+ (_Bool)isAvailableForConfiguration;
+ (unsigned long long)requiredCapabilities;
+ (Class)viewClass;
@property(nonatomic) __weak id <SBCoverSheetSecureAppLaunching> secureAppLauncher; // @synthesize secureAppLauncher=_secureAppLauncher;
@property(nonatomic) _Bool useFakeBlur; // @synthesize useFakeBlur=_useFakeBlur;
@property(readonly, nonatomic) SBDashBoardCombinedListViewController *combinedListViewController; // @synthesize combinedListViewController=_combinedListViewController;
- (void).cxx_destruct;
- (void)_updateCallToActionTextAnimated:(_Bool)arg1;
- (double)_listWidth;
- (void)_updateMediaControlsVisibility;
- (void)_addOrRemoveViewsAsAppropriate;
- (void)_addOrRemoveNotificationsListIfNecessaryAnimated:(_Bool)arg1;
- (void)_addOrRemoveLogoutButtonViewController;
- (void)_addOrRemoveUserPictureViewController;
- (void)_addStatusTextViewControllerIfNecessary;
- (void)_addCallToAction;
- (id)_dashBoardMainPageView;
- (void)combinedListViewControllerHasScrolledSignificantly:(_Bool)arg1;
- (id)notificationSectionSettingsForCombinedListViewController:(id)arg1;
- (void)combinedListViewController:(id)arg1 hasContent:(_Bool)arg2;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)nowPlayingController:(id)arg1 didChangeToState:(long long)arg2;
- (_Bool)isNotificationContentExtensionVisible:(id)arg1;
- (void)updateNotificationSectionSettings:(id)arg1;
- (void)withdrawNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (void)updateNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (void)postNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
@property(nonatomic) __weak id <SBDashBoardNotificationDispatcher> dispatcher; // @dynamic dispatcher;
- (void)dashBoardStatusTextViewControllerContentDidChange:(id)arg1;
- (_Bool)handleEvent:(id)arg1;
@property(readonly, nonatomic) long long scrollingStrategy;
- (void)updateForPresentation:(id)arg1;
- (void)aggregateBehavior:(id)arg1;
- (void)aggregateAppearance:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)updateCallToActionForMesaMatchFailure;
@property(readonly, nonatomic, getter=isShowingMediaControls) _Bool showingMediaControls;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy, nonatomic) SBDashBoardAppearance *activeAppearance;
@property(readonly, copy, nonatomic) SBDashBoardBehavior *activeBehavior;
@property(readonly, copy, nonatomic) NSString *appearanceIdentifier;
@property(readonly, nonatomic) _Bool authenticated;
@property(readonly, nonatomic) UIColor *backgroundColor;
@property(readonly, nonatomic) long long backgroundStyle;
@property(readonly, copy, nonatomic) NSSet *components;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
@property(nonatomic) __weak id <SBDashBoardViewControllerProtocol> dashBoardViewController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, copy, nonatomic) SBDashBoardPresentation *externalPresentation;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) long long idleTimerDuration;
@property(readonly, nonatomic) long long idleTimerMode;
@property(readonly, nonatomic) long long idleWarnMode;
@property(readonly, nonatomic) _UILegibilitySettings *legibilitySettings;
@property(readonly, nonatomic) long long notificationBehavior;
@property(readonly, nonatomic) long long participantState;
@property(readonly, nonatomic) long long presentationAltitude;
@property(readonly, nonatomic) __weak id <UICoordinateSpace> presentationCoordinateSpace;
@property(readonly, nonatomic) long long presentationPriority;
@property(readonly, copy, nonatomic) NSArray *presentationRegions;
@property(readonly, nonatomic) long long presentationStyle;
@property(readonly, nonatomic) long long presentationTransition;
@property(readonly, nonatomic) long long presentationType;
@property(nonatomic) __weak id <SBDashBoardViewPresenting> presenter;
@property(readonly, nonatomic) long long proximityDetectionMode;
@property(readonly, nonatomic) unsigned long long restrictedCapabilities;
@property(readonly) Class superclass;
@property(nonatomic, getter=isTransitioning) _Bool transitioning;

@end

