//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

#import "SBSpotlightMultiplexingViewControllerDelegate.h"
#import "SBViewControllerTransitionContextDelegate.h"

@class NSString, SBSearchBackdropView, UIViewController<SBSpotlightInitiating>, _SBDashBoardSpotlightViewController;

@interface SBDashBoardSpotlightViewController : SBDashBoardViewControllerBase <SBSpotlightMultiplexingViewControllerDelegate, SBViewControllerTransitionContextDelegate>
{
    SBSearchBackdropView *_backdropView;
    UIViewController<SBSpotlightInitiating> *_initiatingViewController;
    id <SBDashBoardSpotlightViewControllerDelegate> _spotlightViewControllerDelegate;
    _SBDashBoardSpotlightViewController *_spotlightViewController;
}

@property(retain, nonatomic) _SBDashBoardSpotlightViewController *spotlightViewController; // @synthesize spotlightViewController=_spotlightViewController;
@property(nonatomic) __weak id <SBDashBoardSpotlightViewControllerDelegate> spotlightViewControllerDelegate; // @synthesize spotlightViewControllerDelegate=_spotlightViewControllerDelegate;
@property(retain, nonatomic) UIViewController<SBSpotlightInitiating> *initiatingViewController; // @synthesize initiatingViewController=_initiatingViewController;
- (void).cxx_destruct;
- (id)_backdropViewSettingsForStyle;
- (unsigned long long)_searchBackdropLowQualityStyleForStyle;
- (_Bool)_shouldUseDarkTintForStyle;
- (_Bool)_initiallyTransitioningToSpotlight:(id)arg1;
- (_Bool)_transitioningIntoSpotlight:(id)arg1;
- (void)transitionDidFinish:(id)arg1;
- (void)transitionWillFinish:(id)arg1;
- (void)transitionDidReverse:(id)arg1;
- (void)transitionWillBegin:(id)arg1;
- (void)dismissSpotlightWithReason:(unsigned long long)arg1;
- (void)aggregateBehavior:(id)arg1;
- (void)performCustomTransitionToVisible:(_Bool)arg1 withAnimationSettings:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (_Bool)wouldHandleButtonEvent:(id)arg1;
- (_Bool)handleEvent:(id)arg1;
- (long long)idleWarnMode;
- (long long)idleTimerMode;
- (long long)idleTimerDuration;
- (long long)backgroundStyle;
- (id)appearanceIdentifier;
- (long long)presentationTransition;
- (long long)presentationType;
- (long long)presentationStyle;
- (_Bool)presentationCancelsTouches;
- (id)transitionContextToShowSpotlight:(_Bool)arg1 animated:(_Bool)arg2 interactive:(_Bool)arg3;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

