//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewExternalControllerBase.h"

#import "SBUIPasscodeLockViewDelegate.h"

@class NSString, SBFAuthenticationAssertion, SBUIBackgroundView, UIView<SBUIPasscodeLockView_Internal>;

@interface SBDashBoardPasscodeViewController : SBDashBoardViewExternalControllerBase <SBUIPasscodeLockViewDelegate>
{
    _Bool _attemptingUnlock;
    SBFAuthenticationAssertion *_sustainGracePeriodAssertion;
    SBFAuthenticationAssertion *_sustainAuthenticationAssertion;
    unsigned long long _options;
    UIView<SBUIPasscodeLockView_Internal> *_passcodeLockView;
    SBUIBackgroundView *_backgroundView;
    id <SBDashBoardPasscodeViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SBDashBoardPasscodeViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_passcodeLockViewPasscodeEntered:(id)arg1 viaMesa:(_Bool)arg2;
- (void)_setBiometricAuthenticationEnabledForTransientAppearanceTransition:(_Bool)arg1;
- (_Bool)handleEvent:(id)arg1;
- (long long)presentationTransition;
- (long long)presentationPriority;
- (long long)presentationType;
- (long long)presentationStyle;
- (void)passcodeLockViewEmergencyCallButtonPressed:(id)arg1;
- (void)passcodeLockViewCancelButtonPressed:(id)arg1;
- (void)passcodeLockViewPasscodeEnteredViaMesa:(id)arg1;
- (void)passcodeLockViewPasscodeEntered:(id)arg1;
- (void)passcodeLockViewPasscodeDidChange:(id)arg1;
- (void)performCustomTransitionToVisible:(_Bool)arg1 withAnimationSettings:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)displayLayoutElementIdentifier;
- (void)aggregateBehavior:(id)arg1;
- (void)aggregateAppearance:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithOptions:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

