//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardPageViewBase.h"

@class UIScrollView, UIView;

@interface SBDashBoardTodayPageView : SBDashBoardPageViewBase
{
    UIView *_todayView;
    UIView *_weatherView;
    UIScrollView *_widgetMajorScrollView;
    double _navigationBarTopInset;
    struct CGPoint _weatherViewOffset;
}

@property(nonatomic) struct CGPoint weatherViewOffset; // @synthesize weatherViewOffset=_weatherViewOffset;
@property(nonatomic) double navigationBarTopInset; // @synthesize navigationBarTopInset=_navigationBarTopInset;
@property(retain, nonatomic) UIScrollView *widgetMajorScrollView; // @synthesize widgetMajorScrollView=_widgetMajorScrollView;
@property(retain, nonatomic) UIView *weatherView; // @synthesize weatherView=_weatherView;
@property(retain, nonatomic) UIView *todayView; // @synthesize todayView=_todayView;
- (void).cxx_destruct;
- (void)_updateContentInsetsForScrollView:(id)arg1;
- (void)_layoutWeatherView;
- (void)_layoutTodayView;
- (void)updateContentInsets;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

