//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

#import "SBDashBoardDateViewScrolling.h"
#import "SBDashBoardStatusBarBackgroundIntersecting.h"
#import "SPUISearchViewControllerDelegate.h"
#import "WGWidgetGroupViewControllerDelegate.h"

@class NSSet, NSString, SBDashBoardComponent, SBDashBoardPageViewController, SBDashBoardTodayPageView, SBViewControllerTransitionContext, UIView, WALockscreenWidgetViewController, WGWidgetGroupViewController;

@interface SBDashBoardTodayViewController : SBDashBoardViewControllerBase <WGWidgetGroupViewControllerDelegate, SPUISearchViewControllerDelegate, SBDashBoardStatusBarBackgroundIntersecting, SBDashBoardDateViewScrolling>
{
    _Bool _runningOnPad;
    SBDashBoardComponent *_dateViewComponent;
    SBDashBoardComponent *_statusBarBackgroundComponent;
    NSSet *_contentViews;
    WGWidgetGroupViewController *_todayViewController;
    WALockscreenWidgetViewController *_weatherViewController;
    UIView *_fakeCanvasView;
    _Bool _pullToSearchPossible;
    _Bool _pullToSearchRecognizing;
    _Bool transitionedToSearchInteractively;
    _Bool _scrollViewContentOffsetDirty;
    struct CGPoint _scrollViewLastContentOffset;
    id <SBDashBoardTodayViewControllerDelegate> _todayViewControllerDelegate;
    SBDashBoardPageViewController *_pageController;
    SBViewControllerTransitionContext *_transitionContext;
}

+ (double)verticalSpacingBetweenWidgets;
+ (_Bool)_isPortrait;
+ (Class)viewClass;
@property(retain, nonatomic) SBViewControllerTransitionContext *transitionContext; // @synthesize transitionContext=_transitionContext;
@property(nonatomic) __weak SBDashBoardPageViewController *pageController; // @synthesize pageController=_pageController;
@property(nonatomic) __weak id <SBDashBoardTodayViewControllerDelegate> todayViewControllerDelegate; // @synthesize todayViewControllerDelegate=_todayViewControllerDelegate;
- (void).cxx_destruct;
- (_Bool)_allowsDateViewScroll;
- (void)_widgetEditViewDidDisappearImplementation;
- (void)_widgetEditViewDidDisappear:(id)arg1;
- (void)_widgetEditViewWillAppear:(id)arg1;
- (id)_majorScrollView;
- (void)_weatherWidgetVisibilityChanged;
- (_Bool)_deviceSupportsWeatherDisplay;
- (id)_dateMovingScrollView;
- (double)_maxClippingOffset;
- (double)_topContentInsetForNavigationBar:(id)arg1;
- (double)_totalDistanceForBlurTransition;
- (id)_searchNavigationBar;
- (void)_updateAppearanceForScrollView:(id)arg1 animated:(_Bool)arg2;
- (void)_updateAppearanceForScrollView:(id)arg1;
- (void)_updateAppearance;
- (void)_updateBehavior;
- (void)_evaluateContentViews;
- (void)_updateContentInsets;
- (void)_initializeWeatherViewControllerIfNecessary;
- (void)_initializeTodayViewControllerIfNecessary;
- (void)_prepareChildViewControllersIfNecessary;
- (void)_setWeatherViewController:(id)arg1;
- (void)_setTodayViewController:(id)arg1;
- (void)updateAppearanceForStatusBarBackgroundHidden:(_Bool)arg1;
@property(readonly, nonatomic) double distanceFromBarToContent;
- (void)updateAppearanceForHidden:(_Bool)arg1 offset:(struct CGPoint)arg2;
@property(readonly, nonatomic) double topContentInset;
@property(readonly, nonatomic) double clippingOffset;
- (void)handleScrollingEnded:(id)arg1;
- (void)handleDraggingWillEndWithTargetContentOffset:(inout struct CGPoint *)arg1 forScrollView:(id)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (_Bool)pullDownSearchGestureDraggingFromTopOfScrollView:(id)arg1;
- (double)pullDownSearchGesturePercentComplete;
- (double)pullDownSearchGestureYOffset;
- (struct UIEdgeInsets)widgetListViewEdgeInsetsIncludingSearchHeader:(_Bool)arg1;
- (id)additionalBundleIdentifiersForAttribution:(id)arg1;
- (void)dismissSearchViewWithReason:(unsigned long long)arg1;
- (void)searchFieldDidFocus;
- (long long)participantState;
- (long long)idleWarnMode;
- (long long)idleTimerMode;
- (long long)idleTimerDuration;
- (id)components;
- (long long)backgroundStyle;
- (_Bool)isWidgetExtensionWithIdentifierVisible:(id)arg1;
- (void)resetForSpotlightDismissalAnimated:(_Bool)arg1;
- (void)updateAccessoryLegibility;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) SBDashBoardTodayPageView *view; // @dynamic view;

@end

