//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardNowPlayingViewController.h"

@class UIView;

@interface SBDashBoardMediaArtworkViewController : SBDashBoardNowPlayingViewController
{
    UIView *_artworkView;
}

+ (Class)viewClass;
- (void).cxx_destruct;
- (long long)presentationPriority;
- (long long)presentationType;
- (void)updateForPresentation:(id)arg1;
- (void)viewDidLoad;
- (id)initWithArtworkView:(id)arg1;

@end

