//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class SBDashBoardPasscodeViewController;

@protocol SBDashBoardPasscodeViewControllerDelegate
- (void)passcodeViewController:(SBDashBoardPasscodeViewController *)arg1 didCompletePasscodeEntry:(_Bool)arg2;
- (void)passcodeViewControllerDidCancelPasscodeEntry:(SBDashBoardPasscodeViewController *)arg1;
- (void)passcodeViewControllerDidBeginPasscodeEntry:(SBDashBoardPasscodeViewController *)arg1;
@end

