//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBApplicationSceneViewControlling.h"

@class SBDeviceApplicationSceneHandle;

@protocol SBDeviceApplicationSceneViewControlling <SBApplicationSceneViewControlling>
@property(nonatomic, getter=isStatusBarHidden) _Bool statusBarHidden;
@property(readonly, nonatomic) SBDeviceApplicationSceneHandle *sceneHandle;
- (void)setStatusBarHidden:(_Bool)arg1 animated:(_Bool)arg2;
@end

