//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBApplicationSceneView.h"

#import "SBAppSwitcherPageContentView.h"
#import "_UISettingsKeyObserver.h"

@class NSString, SBApplicationSceneViewStatusBarDescriptor, SBDeviceApplicationSceneHandle, SBSceneHandleBlockObserver, UIApplicationSceneClientSettingsDiffInspector, UIView<SBApplicationSceneBackgroundView>;

@interface SBDeviceApplicationSceneView : SBApplicationSceneView <_UISettingsKeyObserver, SBAppSwitcherPageContentView>
{
    SBSceneHandleBlockObserver *_sceneHandleObserver;
    UIApplicationSceneClientSettingsDiffInspector *_clientSettingsInspector;
    SBApplicationSceneViewStatusBarDescriptor *_statusBarDescriptor;
}

@property(retain, nonatomic) SBApplicationSceneViewStatusBarDescriptor *statusBarDescriptor; // @synthesize statusBarDescriptor=_statusBarDescriptor;
- (void).cxx_destruct;
- (void)_sceneHandleDidUpdateClientSettingsWithDiff:(id)arg1 transitionContext:(id)arg2;
- (void)_updateStatusBarVisibilityForHostView;
- (long long)_wallpaperStyle;
@property(nonatomic) double cornerRadius;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (id)deviceApplicationSceneView;
- (_Bool)_representsTranslucentContent;
- (void)_configureSceneLiveHostView:(id)arg1;
- (void)_configureSceneSnapshotContext:(id)arg1;
- (void)_refresh;
- (void)layoutSubviews;
- (void)invalidate;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool forcesStatusBarHidden;
@property(retain, nonatomic) UIView<SBApplicationSceneBackgroundView> *backgroundView; // @dynamic backgroundView;
- (void)dealloc;
- (id)initWithSceneHandle:(id)arg1 referenceSize:(struct CGSize)arg2 orientation:(long long)arg3 hostRequester:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long orientation;
@property(readonly, nonatomic) SBDeviceApplicationSceneHandle *sceneHandle; // @dynamic sceneHandle;
@property(readonly) Class superclass;

@end

