//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBRootIconListView.h"

@interface SBDockIconListView : SBRootIconListView
{
    long long _layoutStyle;
    double _spacing;
    unsigned long long _minimumNumberOfIconsToDistributeEvenlyToEdges;
}

+ (unsigned long long)defaultIconContentType;
+ (unsigned long long)iconRowsForInterfaceOrientation:(long long)arg1;
+ (unsigned long long)iconColumnsForInterfaceOrientation:(long long)arg1;
+ (unsigned long long)iconColumnsOrRows;
+ (double)defaultHeight;
@property(nonatomic) unsigned long long minimumNumberOfIconsToDistributeEvenlyToEdges; // @synthesize minimumNumberOfIconsToDistributeEvenlyToEdges=_minimumNumberOfIconsToDistributeEvenlyToEdges;
@property(nonatomic) double spacing; // @synthesize spacing=_spacing;
@property(nonatomic) long long layoutStyle; // @synthesize layoutStyle=_layoutStyle;
- (struct CGSize)intrinsicContentSize;
- (struct CGPoint)originForIconAtCoordinate:(struct SBIconCoordinate)arg1;
- (double)_additionalVerticalInsetToCenterIcons;
- (double)_additionalHorizontalInsetToCenterIcons;
- (unsigned long long)rowAtPoint:(struct CGPoint)arg1;
- (id)iconAtPoint:(struct CGPoint)arg1 index:(unsigned long long *)arg2 proposedOrder:(int *)arg3;
- (unsigned long long)iconsInColumnForSpacingCalculation;
- (unsigned long long)iconsInRowForSpacingCalculation;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (_Bool)allowsAddingIconCount:(unsigned long long)arg1;
- (long long)iconLocation;
- (id)initWithModel:(id)arg1 orientation:(long long)arg2 viewMap:(id)arg3;

@end

