//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBGrabberTongue.h"

@class SBFluidSwitcherScreenEdgePanGestureRecognizer, SBFluidSwitcherViewController;

@interface SBFluidSwitcherGrabberTongue : SBGrabberTongue
{
    SBFluidSwitcherViewController *_switcherViewController;
    SBFluidSwitcherScreenEdgePanGestureRecognizer *_fluidSwitcherEdgePullGestureRecognizer;
}

- (void).cxx_destruct;
- (void)_updateCancelsTouchesWithRecognizer:(id)arg1;
- (id)_createEdgePullGestureRecognizerWithAction:(SEL)arg1;
- (id)initWithDelegate:(id)arg1 switcherViewController:(id)arg2 edge:(unsigned long long)arg3 type:(unsigned long long)arg4;
- (id)initWithDelegate:(id)arg1 edge:(unsigned long long)arg2 type:(unsigned long long)arg3;

// Remaining properties
@property(readonly, nonatomic) __weak id <SBFluidSwitcherGrabberTongueDelegate> delegate; // @dynamic delegate;

@end

