//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SBDockIconListView, SBFloatingDockPlatterView;

@interface SBFloatingDockView : UIView
{
    SBDockIconListView *_userIconListView;
    SBDockIconListView *_recentIconListView;
    SBFloatingDockPlatterView *_mainPlatterView;
    UIView *_dividerView;
    double _iconContentScale;
}

+ (double)contentHeightForBounds:(struct CGRect)arg1 mainPlatterViewFrame:(struct CGRect)arg2;
+ (struct CGSize)_maxIconSize;
+ (double)_maxPlatterHeight;
+ (double)_maxInterIconSpacing;
+ (double)maximumDockContinuousCornerRadius;
+ (double)_referenceInterIconSpacing;
+ (struct CGSize)_referenceIconSize;
@property(nonatomic) double iconContentScale; // @synthesize iconContentScale=_iconContentScale;
@property(retain, nonatomic) UIView *dividerView; // @synthesize dividerView=_dividerView;
@property(retain, nonatomic) SBFloatingDockPlatterView *mainPlatterView; // @synthesize mainPlatterView=_mainPlatterView;
@property(retain, nonatomic) SBDockIconListView *recentIconListView; // @synthesize recentIconListView=_recentIconListView;
@property(retain, nonatomic) SBDockIconListView *userIconListView; // @synthesize userIconListView=_userIconListView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)getMetrics:(CDStruct_368eab7c *)arg1 forBounds:(struct CGRect)arg2;
@property(readonly, nonatomic) double interIconSpacing;
- (double)contentHeightForBounds:(struct CGRect)arg1;
@property(readonly, nonatomic) double contentHeight;
@property(readonly, nonatomic) struct CGRect platterFrame;
- (id)initWithFrame:(struct CGRect)arg1;

@end

