//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImageView, _SBFloatingDockPlatterMetrics, _UIBackdropView;

@interface SBFloatingDockPlatterView : UIView
{
    double _referenceHeight;
    double _maximumContinuousCornerRadius;
    _UIBackdropView *_backgroundView;
    UIImageView *_shadowView;
    _SBFloatingDockPlatterMetrics *_metrics;
}

+ (id)backgroundTintColor;
@property(retain, nonatomic) _SBFloatingDockPlatterMetrics *metrics; // @synthesize metrics=_metrics;
@property(retain, nonatomic) UIImageView *shadowView; // @synthesize shadowView=_shadowView;
@property(retain, nonatomic) _UIBackdropView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) double maximumContinuousCornerRadius; // @synthesize maximumContinuousCornerRadius=_maximumContinuousCornerRadius;
@property(readonly, nonatomic) double referenceHeight; // @synthesize referenceHeight=_referenceHeight;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)_shadowImageForMetrics:(id)arg1;
- (id)_shadowImageViewForMetrics:(id)arg1;
- (id)_metricsForBounds:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(copy, nonatomic) NSString *backdropGroupName;
- (id)initWithReferenceHeight:(double)arg1 maximumContinuousCornerRadius:(double)arg2;

@end

