//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"
#import "BSTransactionObserver.h"
#import "SBSystemGestureRecognizerDelegate.h"
#import "SBTouchTemplateGestureRecognizerDelegate.h"

@class NSString, SBAppLayout, SBAppSwitcherSettings, SBFluidSwitcherGestureWorkspaceTransaction, SBFluidSwitcherScreenEdgePanGestureRecognizer, SBFluidSwitcherViewController, SBScrunchSystemGestureRecognizer;

@interface SBFluidSwitcherGestureManager : NSObject <SBSystemGestureRecognizerDelegate, SBTouchTemplateGestureRecognizerDelegate, BSTransactionObserver, BSDescriptionProviding>
{
    _Bool _gridSwitcherPanIsLatched;
    id <SBFluidSwitcherGestureManagerDelegate> _delegate;
    SBFluidSwitcherViewController *_switcherViewController;
    SBFluidSwitcherGestureWorkspaceTransaction *_activeGestureTransaction;
    SBAppSwitcherSettings *_appSwitcherSettings;
    double _gestureStartTime;
    SBFluidSwitcherScreenEdgePanGestureRecognizer *_gridBottomEdgePanGestureRecognizer;
    SBScrunchSystemGestureRecognizer *_gridScrunchToHomeGestureRecognizer;
}

@property(retain, nonatomic) SBScrunchSystemGestureRecognizer *gridScrunchToHomeGestureRecognizer; // @synthesize gridScrunchToHomeGestureRecognizer=_gridScrunchToHomeGestureRecognizer;
@property(retain, nonatomic) SBFluidSwitcherScreenEdgePanGestureRecognizer *gridBottomEdgePanGestureRecognizer; // @synthesize gridBottomEdgePanGestureRecognizer=_gridBottomEdgePanGestureRecognizer;
@property(nonatomic) double gestureStartTime; // @synthesize gestureStartTime=_gestureStartTime;
@property(nonatomic) _Bool gridSwitcherPanIsLatched; // @synthesize gridSwitcherPanIsLatched=_gridSwitcherPanIsLatched;
@property(retain, nonatomic) SBAppSwitcherSettings *appSwitcherSettings; // @synthesize appSwitcherSettings=_appSwitcherSettings;
@property(retain, nonatomic) SBFluidSwitcherGestureWorkspaceTransaction *activeGestureTransaction; // @synthesize activeGestureTransaction=_activeGestureTransaction;
@property(nonatomic) __weak SBFluidSwitcherViewController *switcherViewController; // @synthesize switcherViewController=_switcherViewController;
@property(nonatomic) __weak id <SBFluidSwitcherGestureManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (_Bool)_isTransactionRunningForGestureRecognizer:(id)arg1;
- (Class)_fluidSwitcherGestureTransactionClassForGestureType:(long long)arg1;
- (long long)_gestureTypeForGestureRecognizer:(id)arg1;
- (_Bool)_shouldBeginGridScrunchGesture:(id)arg1;
- (_Bool)_shouldBeginBottomEdgePanGesture:(id)arg1;
- (void)transactionDidComplete:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)viewForSystemGestureRecognizer:(id)arg1;
- (void)_startFluidSwitcherTransactionWithLabel:(id)arg1 gestureRecognizer:(id)arg2 gestureType:(long long)arg3 checkGestureStatus:(_Bool)arg4;
- (void)_switcherGestureBegan:(id)arg1;
- (void)_handleGridSwitcherPanGesture:(id)arg1;
- (void)_handleScrunchGesture:(id)arg1;
@property(readonly, nonatomic) SBAppLayout *selectedAppLayout;
- (void)dealloc;
- (id)initWithFluidSwitcherViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

