//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBFolderStatsQueryableMetric : NSObject
{
    CDUnknownBlockType _registeredBuilder;
}

- (void).cxx_destruct;
- (void)_handleSignificantTimeChanged;
- (void)registerWithDataBuilder:(CDUnknownBlockType)arg1;
- (id)init;

@end

