//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBFluidSwitcherPersonality.h"
#import "_UISettingsKeyObserver.h"

@class NSString, SBAppSwitcherSettings, SBFluidSwitcherViewController;

@interface SBGridSwitcherPersonality : NSObject <_UISettingsKeyObserver, SBFluidSwitcherPersonality>
{
    struct CGPoint _initialTouchOffsetFromCenter;
    SBAppSwitcherSettings *_settings;
    SBFluidSwitcherViewController *_switcherViewController;
}

@property(nonatomic) __weak SBFluidSwitcherViewController *switcherViewController; // @synthesize switcherViewController=_switcherViewController;
- (void).cxx_destruct;
- (void)_applyPrototypeSettingsToConstants;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (_Bool)_isSwipeGestureFromHomeScreen;
- (_Bool)_inactiveCardsHidden;
- (struct CGRect)_frameWithScaleAppliedForIndex:(unsigned long long)arg1 mode:(long long)arg2 ignoringScrollOffset:(_Bool)arg3 ignoreInsertionsAndRemovals:(_Bool)arg4;
- (double)_effectiveVerticalSpacing;
- (double)_effectiveHorizontalSpacing;
- (unsigned long long)_numberOfColsForNumberOfItems:(unsigned long long)arg1;
- (unsigned long long)_numberOfCols;
- (unsigned long long)_colForCardIndex:(unsigned long long)arg1;
- (unsigned long long)_rowForCardIndex:(unsigned long long)arg1;
- (struct CGRect)_containerViewBounds;
- (double)_scaleForHomeScreenIconZoom;
- (struct CGRect)_iconImageFrameForHomeScreenIconZoom;
- (double)dockProgress;
- (double)_progressSwipingHomeToSwitcher;
- (double)_gridSwipeUpGestureProgressToMaxTranslation;
- (double)_gridSwipeUpPanTranslationForFullTransition;
- (double)_gridSwipeUpGestureTranslation;
- (long long)_currentUnlockedEnvironmentMode;
- (void)_getActiveGestureFromUnlockedEnvironmentMode:(long long *)arg1 toUnlockedEnvironmentMode:(long long *)arg2;
- (unsigned long long)_cardIndexForIndex:(unsigned long long)arg1;
- (unsigned long long)_indexForCardIndex:(unsigned long long)arg1;
- (_Bool)_enableCarryUI;
- (_Bool)shouldHurdleDockForIconZooms;
- (_Bool)canActivateControlCenter;
- (_Bool)shouldScrollWhenActivatingAppLayoutAtIndex:(unsigned long long)arg1;
- (id)appLayoutUnderWhichToAddDimmingView;
- (id)appLayoutForHomeScreenIconZoom;
- (id)topMostAppLayout;
- (double)dimmingAlpha;
- (double)baseHysteresisForStartingKillGesture;
- (double)wallpaperScale;
- (double)homeScreenScale;
- (double)homeScreenBlurProgress;
- (double)homeScreenAlpha;
- (double)switcherOpacity;
- (double)_cardCornerRadiusInAppSwitcher;
- (double)_cardCornerRadiusInApplicationDuringTransition:(_Bool)arg1;
- (double)cardCornerRadiusForIndex:(unsigned long long)arg1;
- (double)shadowOpacityForIndex:(unsigned long long)arg1;
- (double)titleOpacityForIndex:(unsigned long long)arg1;
- (double)titleAndIconOpacityForIndex:(unsigned long long)arg1;
- (double)opacityForIndex:(unsigned long long)arg1;
- (struct CGSize)interpageSpacingForPaging;
- (_Bool)scrollViewPagingEnabled;
- (double)leadingOffsetToOffset:(double)arg1;
- (struct CGPoint)restingOffsetForScrollOffset:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2;
- (struct CGPoint)_restingOffsetForScrollOffset:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2;
- (struct CGPoint)contentOffsetForIndex:(unsigned long long)arg1 ignoreInsertionsAndRemovals:(_Bool)arg2;
- (struct UIEdgeInsets)contentInset;
- (struct CGSize)contentSize;
- (double)decelerationRate;
- (id)switcherScrollView;
- (double)switcherCardScale;
- (double)snapshotScale;
- (id)itemsToKeepInHierarchyDuringAnimationForInsertion:(_Bool)arg1 direction:(unsigned long long)arg2 visibleItemRange:(struct _NSRange)arg3;
- (void)getIndicesToPreserveScrollPositionForInsertionOrRemovalAtIndex:(unsigned long long)arg1 isInserting:(_Bool)arg2 visibleItemRange:(struct _NSRange)arg3 startingScrollIndex:(unsigned long long *)arg4 finalScrollIndex:(unsigned long long *)arg5 animated:(_Bool)arg6;
- (unsigned long long)movementDirectionForInsertionOrRemovalAtIndex:(unsigned long long)arg1 isInserting:(_Bool)arg2;
- (_Bool)shouldAnimateInsertionOrRemovalAtIndex:(unsigned long long)arg1 visibleItemRange:(struct _NSRange)arg2;
- (void)didRemoveAppLayout:(id)arg1 fromIndex:(unsigned long long)arg2;
- (void)didInsertAppLayout:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)scrollViewKillingProgressUpdated:(double)arg1 ofAppLayout:(id)arg2;
- (_Bool)isIndexVisible:(unsigned long long)arg1 ignoreInsertionsAndRemovals:(_Bool)arg2;
- (double)containerViewWidthAtGridScale;
- (double)_gridScrunchGestureScalingProgress;
- (double)_gridSwipeUpGestureScalingProgressForIndex:(unsigned long long)arg1;
- (double)_dockHeightForSwipeGesture;
- (double)_scaleForCardIndex:(unsigned long long)arg1 mode:(long long)arg2 ignoringGesture:(_Bool)arg3;
- (double)_scaleForIndex:(unsigned long long)arg1 mode:(long long)arg2 ignoringGesture:(_Bool)arg3;
- (double)scaleForIndex:(unsigned long long)arg1 mode:(long long)arg2;
- (double)_scaleForSwipingUpToSwitcherForIndex:(unsigned long long)arg1;
- (double)_scaleForSwipingAppUpToSwitcher;
- (double)_scaleForSwipingHomeToSwitcher;
- (struct CGRect)_frameForCardIndex:(unsigned long long)arg1 withCardSize:(struct CGSize)arg2 mode:(long long)arg3 ignoringGesture:(_Bool)arg4 ignoreInsertionsAndRemovals:(_Bool)arg5;
- (struct CGRect)_frameForIndex:(unsigned long long)arg1 withCardSize:(struct CGSize)arg2 mode:(long long)arg3 ignoringScrollOffset:(_Bool)arg4 ignoringGesture:(_Bool)arg5 ignoreInsertionsAndRemovals:(_Bool)arg6;
- (struct CGRect)_adjustedFrameForSwitcherBringUp:(struct CGRect)arg1 index:(unsigned long long)arg2 appLayout:(id)arg3;
- (struct CGRect)frameForIndex:(unsigned long long)arg1 mode:(long long)arg2;
- (struct CGRect)_offsetControlCenterRect:(struct CGRect)arg1 forSwitcherBringupProgress:(double)arg2 scale:(double)arg3;
- (struct CGRect)_offsetCardRect:(struct CGRect)arg1 forSwitcherBringupProgress:(double)arg2 scale:(double)arg3;
- (double)_switcherBringupControlCenterSliceWidth;
- (struct CGRect)_transformedRect:(struct CGRect)arg1 forScale:(double)arg2;
- (struct CGPoint)_scalingAnchorPoint;
- (struct CGRect)_controlCenterLayoutFrame;
- (struct CGRect)_controlCenterFrame;
- (double)_containerToCardsBottomMargin;
- (double)_containerToCardsTopMargin;
- (double)_cardsSectionActualHeight;
- (double)_cardsSectionNaturalHeight;
- (id)_controlCenterSnapHeights;
- (struct UIEdgeInsets)_controlCenterEdgeInsets;
- (struct CGSize)_controlCenterLayoutSize;
- (_Bool)_controlCenterIsVerticallyCentered;
- (struct CGSize)_controlCenterSize;
- (double)_gridSwitcherPageScale;
- (long long)updateModeForActiveGesture;
- (void)didBeginGesture:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

