//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class NSArray, NSCountedSet, NSMapTable, NSMutableSet, NSSet, NSString, SBIconView;

@interface SBIconDragContext : NSObject <BSDescriptionProviding>
{
    NSMapTable *_iconOrigins;
    NSMutableSet *_sourceIconViews;
    NSMapTable *_iconToExpandAfterDropAnimation;
    NSMutableSet *_destinationIconViews;
    NSCountedSet *_messageExpectations;
    NSMutableSet *_enteredIconListViews;
    NSMapTable *_targetsForCancellingIconViews;
    _Bool _performedIconDrop;
    NSArray *_iconPlaceholders;
    NSArray *_grabbedIconViews;
    NSSet *_itemIdentifiers;
    NSSet *_sourceIcons;
    SBIconView *_primaryIconView;
}

@property(nonatomic) _Bool performedIconDrop; // @synthesize performedIconDrop=_performedIconDrop;
@property(retain, nonatomic) SBIconView *primaryIconView; // @synthesize primaryIconView=_primaryIconView;
@property(copy, nonatomic) NSSet *sourceIcons; // @synthesize sourceIcons=_sourceIcons;
@property(copy, nonatomic) NSSet *itemIdentifiers; // @synthesize itemIdentifiers=_itemIdentifiers;
@property(copy, nonatomic) NSArray *grabbedIconViews; // @synthesize grabbedIconViews=_grabbedIconViews;
@property(copy, nonatomic) NSArray *iconPlaceholders; // @synthesize iconPlaceholders=_iconPlaceholders;
- (void).cxx_destruct;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)targetIconViewForCancellingIconView:(id)arg1;
- (void)setTargetIconView:(id)arg1 forCancellingIconView:(id)arg2;
- (void)addEnteredIconListView:(id)arg1;
- (_Bool)hasEnteredIconListView:(id)arg1;
- (void)enumerateDestinationIconViewsUsingBlock:(CDUnknownBlockType)arg1;
- (void)addDestinationIconView:(id)arg1;
- (id)iconToExpandAfterDropAnimationForDragItem:(id)arg1;
- (void)setIcon:(id)arg1 shouldExpandAfterDropAnimationForDragItems:(id)arg2;
@property(readonly, nonatomic, getter=isWaitingForMessage) _Bool waitingForMessage;
@property(readonly, copy, nonatomic) NSSet *expectedMessages;
- (void)removeAllMessageExpectations;
- (_Bool)hasMessageExpectationNamed:(id)arg1;
- (void)removeMessageExpectationNamed:(id)arg1;
- (void)addMessageExpectationNamed:(id)arg1;
- (void)addSourceIconView:(id)arg1;
- (_Bool)hasSourceIconView:(id)arg1;
- (void)enumerateIconOriginsUsingBlock:(CDUnknownBlockType)arg1;
- (void)setOrigin:(id)arg1 forIcon:(id)arg2;
- (id)originForIcon:(id)arg1;
- (void)addSourceIcons:(id)arg1;
- (void)addSourceIcon:(id)arg1;
- (void)addGrabbedIconView:(id)arg1;
- (void)removeIconPlaceholders:(id)arg1;
- (void)addIconPlaceholders:(id)arg1;
- (void)addIconPlaceholder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

