//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBSDisplayLayoutObserver.h"
#import "SBIdleTimerCoordinating.h"
#import "SBPocketStateMonitorObserver.h"

@class FBSDisplayLayoutMonitor, NSMutableSet, NSString, SBIdleTimerCoordinatorHelper, SBIdleTimerDescriptor, SBIdleTimerProxy;

@interface SBIdleTimerGlobalCoordinator : NSObject <SBPocketStateMonitorObserver, FBSDisplayLayoutObserver, SBIdleTimerCoordinating>
{
    NSMutableSet *_disabledIdleTimerAssertions;
    SBIdleTimerDescriptor *_disabledIdleTimerDescriptor;
    SBIdleTimerDescriptor *_enabledIdleTimerDescriptor;
    id <SBIdleTimerProviding> _lastActiveIdleTimerProvider;
    SBIdleTimerProxy *_idleTimerProxy;
    SBIdleTimerCoordinatorHelper *_idleTimerCoordinatorHelper;
    FBSDisplayLayoutMonitor *_layoutMonitor;
    _Bool _started;
    id <SBIdleTimerGlobalCoordinatorDelegate> _delegate;
    id <SBIdleTimer> _idleTimer;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreateIfNeeded:(_Bool)arg1;
@property(retain, nonatomic, setter=_setIdleTimer:) id <SBIdleTimer> idleTimer; // @synthesize idleTimer=_idleTimer;
@property(nonatomic) __weak id <SBIdleTimerGlobalCoordinatorDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic, setter=_setIdleTimerProxy:) SBIdleTimerProxy *idleTimerProxy; // @synthesize idleTimerProxy=_idleTimerProxy;
- (void).cxx_destruct;
- (void)_windowDidBecomeKey:(id)arg1;
- (void)_screenWillLock;
- (void)_powerStateDidChange;
- (void)_batterySaverModeDidChange;
- (void)_proximityChanged;
- (void)_idleTimerPrefsChanged;
- (void)_setIdleTimer:(id)arg1 forReason:(id)arg2;
- (void)_setEnabledIdleTimerDescriptor:(id)arg1 reason:(id)arg2;
- (void)_setIdleTimerDescriptor:(id)arg1 forReason:(id)arg2;
- (id)_updateIdleTimerForProvider:(id)arg1 descriptor:(id)arg2 forReason:(id)arg3;
- (id)_activeIdleTimerProvider;
- (void)layoutMonitor:(id)arg1 didUpdateDisplayLayout:(id)arg2 withContext:(id)arg3;
- (void)pocketStateMonitor:(id)arg1 pocketStateDidChangeFrom:(long long)arg2 to:(long long)arg3;
- (id)idleTimerProvider:(id)arg1 didProposeDescriptor:(id)arg2 reason:(id)arg3;
- (void)updateIdleTimerForReason:(id)arg1;
- (_Bool)isIdleTimerEnabled;
- (_Bool)isIdleTimerDisabledForReason:(id)arg1;
- (void)setIdleTimerDisabled:(_Bool)arg1 forReason:(id)arg2;
- (void)resetIdleTimer;
- (void)start;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

