//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBHardwareButtonGestureParametersProviderBase.h"

#import "SBHardwareButtonGestureParametersObserver.h"

@class NSString, SBAccessibilityHardwareButtonInteraction, SBHardwareButtonGestureParameters, SBHardwareButtonService, SBSiriHardwareButtonInteraction, SBWalletPreArmController;

@interface SBLockHardwareButtonActions : SBHardwareButtonGestureParametersProviderBase <SBHardwareButtonGestureParametersObserver>
{
    _Bool _didPlayLockSound;
    _Bool _dontLockOnNextLockUp;
    _Bool _fadeOutInProgressFromLockButtonWhileUnlocked;
    _Bool _undidFadeOutFromLockButton;
    _Bool _sosGestureIsActive;
    long long _homeButtonType;
    SBHardwareButtonService *_hardwareButtonService;
    SBWalletPreArmController *_walletPreArmController;
    SBHardwareButtonGestureParameters *_accessibilityGestureParameters;
    SBHardwareButtonGestureParameters *_siriGestureParameters;
    _Bool _isButtonDown;
    SBSiriHardwareButtonInteraction *_siriButtonInteraction;
    SBAccessibilityHardwareButtonInteraction *_accessibilityButtonInteraction;
}

@property(retain, nonatomic) SBAccessibilityHardwareButtonInteraction *accessibilityButtonInteraction; // @synthesize accessibilityButtonInteraction=_accessibilityButtonInteraction;
@property(retain, nonatomic) SBSiriHardwareButtonInteraction *siriButtonInteraction; // @synthesize siriButtonInteraction=_siriButtonInteraction;
@property(readonly, nonatomic) _Bool isButtonDown; // @synthesize isButtonDown=_isButtonDown;
- (void).cxx_destruct;
- (void)provider:(id)arg1 didUpdateButtonGestureParameters:(id)arg2;
- (id)hardwareButtonGestureParameters;
- (void)_playLockSound;
@property(readonly, nonatomic) _Bool shouldWaitForDoublePress; // @dynamic shouldWaitForDoublePress;
- (void)performSOSActionsWithUUID:(id)arg1 triggerMechanism:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)performSOSDidTriggerActions;
- (void)performTriplePressActions;
- (void)performDoublePressActions;
- (void)performSinglePressAction;
- (_Bool)performButtonUpPreActions;
- (void)performLongPressActions;
- (void)performButtonDownActions;
- (void)performFinalButtonUpActions;
- (_Bool)reverseFadeOutIfNeeded;
- (_Bool)performButtonDownPreActions;
- (void)performSOSGestureEndedActions;
- (void)performSOSGestureBeganActions;
- (id)initWithHomeButtonType:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

