//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBHardwareButtonGestureParametersProviderBase.h"

#import "SBHardwareButtonGestureParametersObserver.h"
#import "SBPressPrecedenceArbiter.h"
#import "UIGestureRecognizerDelegate.h"

@class NSString, SBApplication, SBClickGestureRecognizer, SBHardwareButtonGestureParameters, SBHomeHardwareButton, SBLockHardwareButtonActions, SBLongPressGestureRecognizer, SBPressGestureRecognizer, UIGestureRecognizer;

@interface SBLockHardwareButton : SBHardwareButtonGestureParametersProviderBase <UIGestureRecognizerDelegate, SBHardwareButtonGestureParametersObserver, SBPressPrecedenceArbiter>
{
    SBApplication *_lastLockButtonEventRecipient;
    unsigned long long _aggdStartTime;
    SBLockHardwareButtonActions *_buttonActions;
    SBHardwareButtonGestureParameters *_buttonGestureParameters;
    SBPressGestureRecognizer *_buttonDownGestureRecognizer;
    SBClickGestureRecognizer *_singlePressGestureRecognizer;
    SBLongPressGestureRecognizer *_longPressGestureRecognizer;
    SBClickGestureRecognizer *_doublePressGestureRecognizer;
    SBClickGestureRecognizer *_triplePressGestureRecognizer;
    UIGestureRecognizer *_screenshotGestureRecognizer;
    SBHomeHardwareButton *_homeHardwareButton;
    long long _homeButtonType;
}

@property(nonatomic) long long homeButtonType; // @synthesize homeButtonType=_homeButtonType;
@property(nonatomic) __weak SBHomeHardwareButton *homeHardwareButton; // @synthesize homeHardwareButton=_homeHardwareButton;
@property(nonatomic) __weak UIGestureRecognizer *screenshotGestureRecognizer; // @synthesize screenshotGestureRecognizer=_screenshotGestureRecognizer;
@property(retain, nonatomic) SBClickGestureRecognizer *triplePressGestureRecognizer; // @synthesize triplePressGestureRecognizer=_triplePressGestureRecognizer;
@property(retain, nonatomic) SBClickGestureRecognizer *doublePressGestureRecognizer; // @synthesize doublePressGestureRecognizer=_doublePressGestureRecognizer;
@property(retain, nonatomic) SBLongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(retain, nonatomic) SBClickGestureRecognizer *singlePressGestureRecognizer; // @synthesize singlePressGestureRecognizer=_singlePressGestureRecognizer;
@property(retain, nonatomic) SBPressGestureRecognizer *buttonDownGestureRecognizer; // @synthesize buttonDownGestureRecognizer=_buttonDownGestureRecognizer;
@property(retain, nonatomic) SBHardwareButtonGestureParameters *buttonGestureParameters; // @synthesize buttonGestureParameters=_buttonGestureParameters;
@property(retain, nonatomic) SBLockHardwareButtonActions *buttonActions; // @synthesize buttonActions=_buttonActions;
- (void).cxx_destruct;
- (id)hardwareButtonGestureParameters;
- (void)provider:(id)arg1 didUpdateButtonGestureParameters:(id)arg2;
- (void)_reportAggdLoggingForButtonEventIsDownEvent:(_Bool)arg1;
- (_Bool)_shouldHandleVolumeAndPowerButtonPriorities;
- (void)__sendButtonEventToApp:(id)arg1 forRecognizer:(id)arg2;
- (void)_sendButtonUpEventToAppForRecognizer:(id)arg1;
- (_Bool)_tryToSendButtonDownEventsToAppForRecognizer:(id)arg1;
- (void)cancelLongPress;
- (void)triplePress:(id)arg1;
- (void)doublePress:(id)arg1;
- (void)longPress:(id)arg1;
- (void)singlePress:(id)arg1;
- (void)buttonDown:(id)arg1;
- (id)preemptablePressGestureRecognizers;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)reverseFadeOutIfNeeded;
@property(readonly, nonatomic) _Bool isButtonDown;
- (void)_reconfigureButtonGestureRecognizers;
- (void)screenshotRecognizerDidRecognize:(id)arg1;
- (void)_createGestureRecognizers;
- (id)initWithScreenshotGestureRecognizer:(id)arg1 homeHardwareButton:(id)arg2 buttonActions:(id)arg3 homeButtonType:(long long)arg4 createGestures:(_Bool)arg5;
- (id)initWithScreenshotGestureRecognizer:(id)arg1 homeHardwareButton:(id)arg2 homeButtonType:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

