//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAppContainerViewController.h"

#import "SBDeviceApplicationSceneHandleObserver.h"
#import "SBDeviceApplicationSceneViewControlling.h"

@class NSMutableArray, NSString, SBApplicationBlurContentView, SBSceneHandle, UIDropInteraction, UIView;

@interface SBMainWorkspaceApplicationSceneLayoutElementViewController : SBAppContainerViewController <SBDeviceApplicationSceneHandleObserver, SBDeviceApplicationSceneViewControlling>
{
    NSMutableArray *_gestureRecognizers;
    UIDropInteraction *_dropInteraction;
    _Bool _statusBarHidden;
    _Bool _nubViewHidden;
    _Bool _nubViewHighlighted;
    double _darkenViewAlpha;
    double _shadowOpacity;
    double _shadowOffset;
    double _cornerRadius;
}

@property(retain, nonatomic) UIDropInteraction *dropInteraction; // @synthesize dropInteraction=_dropInteraction;
@property(nonatomic) double darkenViewAlpha; // @synthesize darkenViewAlpha=_darkenViewAlpha;
@property(nonatomic, getter=isNubViewHighlighted) _Bool nubViewHighlighted; // @synthesize nubViewHighlighted=_nubViewHighlighted;
@property(nonatomic, getter=isNubViewHidden) _Bool nubViewHidden; // @synthesize nubViewHidden=_nubViewHidden;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) double shadowOffset; // @synthesize shadowOffset=_shadowOffset;
@property(nonatomic) double shadowOpacity; // @synthesize shadowOpacity=_shadowOpacity;
@property(nonatomic, getter=isStatusBarHidden) _Bool statusBarHidden; // @synthesize statusBarHidden=_statusBarHidden;
- (void).cxx_destruct;
- (id)_medusaDecoratedVC:(id)arg1;
- (id)_medusaDecoratedVC;
- (id)mainWorkspaceApplicationSceneLayoutElementViewController;
- (void)sceneHandle:(id)arg1 didChangeEffectiveForegroundness:(_Bool)arg2;
- (void)sceneHandle:(id)arg1 didCreateScene:(id)arg2;
- (void)_configureViewController:(id)arg1;
- (id)_newApplicationSceneViewControllerForSceneHandle:(id)arg1;
- (id)_applicationSceneViewController;
- (_Bool)_shouldDisplayLayoutElementBecomeActive;
- (unsigned long long)supportedContentInterfaceOrientations;
- (void)prepareForReuse;
- (_Bool)nubViewContainsPoint:(struct CGPoint)arg1;
- (void)removeGestureRecognizer:(id)arg1;
- (void)addGestureRecognizer:(id)arg1;
- (void)setStatusBarHidden:(_Bool)arg1 animated:(_Bool)arg2;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic, setter=_setBlurContentView:) SBApplicationBlurContentView *_blurContentView;
@property(readonly, nonatomic, getter=isBlurred) _Bool blurred;
- (void)blurApplicationContent:(_Bool)arg1 withAnimationFactory:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithDisplayIdentity:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) long long contentInterfaceOrientation;
@property(readonly, nonatomic) struct CGSize contentReferenceSize;
@property(retain, nonatomic) UIView *customContentView;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic) long long displayMode;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) id <SBScenePlaceholderContentContext> placeholderContentContext;
@property(readonly, nonatomic) SBSceneHandle *sceneHandle;
@property(readonly) Class superclass;

@end

