//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSceneLayoutViewController.h"

@class FBUIApplicationSceneDeactivationAssertion, NSArray, NSMutableSet, SBMainDisplayLayoutState, SBMainDisplaySceneLayoutDropInteractionManager, SBMainDisplaySceneLayoutGestureManager, SBOrientationTransformWrapperView, UIView;

@interface SBMainDisplaySceneLayoutViewController : SBSceneLayoutViewController
{
    SBMainDisplaySceneLayoutGestureManager *_gestureManager;
    SBMainDisplaySceneLayoutDropInteractionManager *_dropInteractionManager;
    NSMutableSet *_pushPopPrimaryElementReasons;
    NSMutableSet *_pushPopSideElementReasons;
    NSMutableSet *_pushPopSeparatorElementReasons;
    _Bool _showsPushInWallpaper;
    FBUIApplicationSceneDeactivationAssertion *_applicationSceneDeactivationAssertion;
    SBOrientationTransformWrapperView *_contentWrapperView;
    UIView *_contentView;
    UIView *_primaryLayoutElementViewContainerView;
    UIView *_sideLayoutElementViewContainerView;
    UIView *_separatorView;
    UIView *_nubView;
    id _keyboardWillChangeFrameObserver;
    double _separatorViewKeyboardMargin;
    _Bool _nubHighlighted;
    double _separatorViewAlpha;
}

@property(nonatomic, getter=_isNubHighlighted, setter=_setNubHighlighted:) _Bool _nubHighlighted; // @synthesize _nubHighlighted;
@property(nonatomic, setter=_setSeparatorViewAlpha:) double _separatorViewAlpha; // @synthesize _separatorViewAlpha;
- (void).cxx_destruct;
- (struct CGRect)_layoutFrameForLayoutRole:(long long)arg1 spaceConfiguration:(long long)arg2 inBounds:(struct CGRect)arg3;
- (struct CGSize)_layoutSizeForLayoutRole:(long long)arg1 spaceConfiguration:(long long)arg2 interfaceOrientation:(long long)arg3;
- (unsigned int)_convertAnchorEdge:(unsigned int)arg1 toLayoutOrientation:(long long)arg2;
- (unsigned int)_anchorEdgeForLayoutRole:(long long)arg1;
- (struct CGRect)_separatorViewFrame;
- (_Bool)_isStatusBarForceHiddenForLayoutRole:(long long)arg1 spaceConfiguration:(long long)arg2;
- (_Bool)_shouldConsiderHomeScreenAsActive;
- (void)_updateAuxiliaryViews;
- (_Bool)_isLayoutElementViewControllerOccluded:(id)arg1;
- (_Bool)_shouldRotateToLayoutOrientation:(long long)arg1;
- (_Bool)_shouldAdjustViewAffordancesAfterTransition;
- (_Bool)_shouldRepositionViewAfterTransition;
- (_Bool)_shouldDeactivateSceneAndSuppressKeyboard:(id)arg1;
- (_Bool)_layoutStateHasInactiveLayoutElements;
- (void)_doCommonCleanupUponEndingLayoutTransition;
- (void)_beginLayoutStateTransitionWithContext:(id)arg1;
- (id)_layoutElementViewContainerViewForLayoutRole:(long long)arg1;
- (void)_addLayoutElementViewController:(id)arg1 forLayoutElement:(id)arg2 entity:(id)arg3;
- (struct CGRect)referenceFrameForIdentifier:(id)arg1 inLayoutState:(id)arg2;
- (struct CGRect)referenceFrameForEntity:(id)arg1 inLayoutState:(id)arg2;
- (id)_displayConfiguration;
- (id)_applicationSceneLayoutElementControllerForLayoutRole:(long long)arg1;
@property(readonly, copy, nonatomic) NSArray *_transitioningAppViewControllers;
@property(readonly, nonatomic) NSArray *appViewControllers;
- (struct CGRect)_updateRectInReferenceCoordinateSpace:(struct CGRect)arg1 withBlock:(CDUnknownBlockType)arg2;
- (struct CGPoint)_updatePointInReferenceCoordinateSpace:(struct CGPoint)arg1 withBlock:(CDUnknownBlockType)arg2;
- (struct CGAffineTransform)_convertTransformFromContentViewCoordinateSpaceToReferenceCoordinateSpace:(struct CGAffineTransform)arg1;
- (struct CGRect)_convertRectFromContentViewCoordinateSpaceToReferenceCoordinateSpace:(struct CGRect)arg1;
- (struct CGPoint)_convertPointFromContentViewCoordinateSpaceToReferenceCoordinateSpace:(struct CGPoint)arg1;
- (struct CGAffineTransform)_convertTransformFromReferenceCoordinateSpaceToContentViewCoordinateSpace:(struct CGAffineTransform)arg1;
- (struct CGRect)_convertRectFromReferenceCoordinateSpaceToContentViewCoordinateSpace:(struct CGRect)arg1;
- (struct CGPoint)_convertPointFromReferenceCoordinateSpaceToContentViewCoordinateSpace:(struct CGPoint)arg1;
- (id)_separatorView;
- (_Bool)_shouldReverseLayoutDirection;
- (void)_popOutWithElementMask:(unsigned long long)arg1 forReason:(id)arg2 animationFactory:(id)arg3;
- (void)_pushInWithElementMask:(unsigned long long)arg1 forReason:(id)arg2 animationFactory:(id)arg3;
- (struct CGRect)_separatorViewReferenceFrameForSpaceConfiguration:(long long)arg1 interfaceOrientation:(long long)arg2;
- (struct CGRect)_referenceFrameForLayoutRole:(long long)arg1 spaceConfiguration:(long long)arg2 interfaceOrientation:(long long)arg3;
- (struct CGRect)_referenceFrameForLayoutElement:(id)arg1 inLayoutState:(id)arg2;
- (unsigned int)_layoutSpaceAnchorEdgeForLayoutRole:(long long)arg1;
- (double)_layoutWidthForLayoutRole:(long long)arg1 inSpaceConfiguration:(long long)arg2;
- (struct CGRect)_layoutFrameForSize:(struct CGSize)arg1 withRole:(long long)arg2 inInterfaceOrientation:(long long)arg3;
- (void)_requireUnpinPanSystemGestureRecognizerFailureForGestureRecognizer:(id)arg1;
@property(readonly, nonatomic) struct CGRect _separatorViewHitTestFrame;
@property(readonly, nonatomic) double _separatorViewWidth;
- (unsigned int)_anchorEdgeForLayoutRole:(long long)arg1 inInterfaceOrientation:(long long)arg2;
- (void)_orderFrontLayoutElementViewControllerForLayoutRole:(long long)arg1;
- (long long)_overrideInterfaceOrientationMechanics;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithSceneManager:(id)arg1;
- (id)_animationWrapperViewForElement:(id)arg1 entity:(id)arg2 layoutState:(id)arg3;
- (struct CGAffineTransform)_transformForHidingElementWithRole:(long long)arg1 frame:(struct CGRect)arg2 baseTransform:(struct CGAffineTransform)arg3 withLayoutState:(id)arg4;
- (void)_slideOutSideAppWithAnimationSettings:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_fadeOutSideAppWithAnimationSettings:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_rotateAppViewsWithAnimationSettings:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_pushLayoutElementViewController:(id)arg1 withAnimationSettings:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_slideInSideAppWithAnimationSettings:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_fadeInSideAppWithAnimationSettings:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_makeSideAppControllerPrimaryWithAnimationSettings:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_popSideAppControllerWithAnimationSettings:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_pushSideAppOverlayController:(id)arg1 withAnimationSettings:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)_animationSettingsForPushWithDuration:(double)arg1;
- (void)_resizeAppViewsWithAnimationSettings:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_sideAppDismissalAnimationControllerWithTransitionRequest:(id)arg1 animationSettings:(id)arg2;
- (id)_rotateAppsAnimationControllerWithTransitionRequest:(id)arg1;
- (id)_primaryAppSlideOverAnimationControllerWithTransitionRequest:(id)arg1;
- (id)_sideAppPresentationAnimationControllerWithTransitionRequest:(id)arg1 animationSettings:(id)arg2;
- (id)_sideAppMakePrimaryAnimationControllerWithTransitionRequest:(id)arg1;
- (id)_sideAppSlideOutAnimationControllerWithTransitionRequest:(id)arg1;
- (id)_sideAppSlideInAnimationControllerWithTransitionRequest:(id)arg1;
- (id)_resizeAppsAnimationControllerWithTransitionRequest:(id)arg1;
- (id)sideAppAnimationControllerWithTransitionRequest:(id)arg1 animationSettings:(id)arg2;
- (id)composedAnimationControllerForDosidoWithTransitionRequest:(id)arg1 using:(id)arg2;
- (id)animationControllerForRotatingWithTransitionRequest:(id)arg1;
- (id)animationControllerForTransitionRequest:(id)arg1;
- (void)_animateLayoutElementViewController:(id)arg1 inLayoutState:(id)arg2 withAnimationSettings:(id)arg3 animationBlock:(CDUnknownBlockType)arg4 completion:(CDUnknownBlockType)arg5;
- (void)_fadeOutLayoutElementViewController:(id)arg1 inLayoutState:(id)arg2 withAnimationSettings:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_fadeInLayoutElementViewController:(id)arg1 inLayoutState:(id)arg2 withAnimationSettings:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_slideInLayoutElementViewController:(id)arg1 inLayoutState:(id)arg2 withAnimationSettings:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_slideOutLayoutElementViewController:(id)arg1 inLayoutState:(id)arg2 withAnimationSettings:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (double)normalizedDismissRightLocation;
- (double)normalizedWideNarrowLocation;
- (double)normalizedHalfHalfLocation;
- (double)normalizedNarrowWideLocation;
- (double)normalizedDismissLeftLocation;

// Remaining properties
@property(readonly, nonatomic) SBMainDisplayLayoutState *_transitioningFromLayoutState; // @dynamic _transitioningFromLayoutState;
@property(readonly, nonatomic) SBMainDisplayLayoutState *_transitioningToLayoutState; // @dynamic _transitioningToLayoutState;
@property(readonly, nonatomic) SBMainDisplayLayoutState *layoutState; // @dynamic layoutState;

@end

