//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSystemGestureManager.h"

@class SBGestureDefaults;

@interface SBMainDisplaySystemGestureManager : SBSystemGestureManager
{
    SBGestureDefaults *_gestureDefaults;
    _Bool _multitaskingGesturesEnabled;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_updateUserPreferences;
- (_Bool)_isTouchGestureWithType:(unsigned long long)arg1;
- (_Bool)_shouldEnableSystemGestureWithType:(unsigned long long)arg1;
- (_Bool)_isGestureWithTypeAllowed:(unsigned long long)arg1;
- (void)_evaluateEnablement;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)_init;
- (id)_initWithDisplayIdentity:(id)arg1;

@end

