//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSystemGestureWorkspaceTransaction.h"

#import "BSTransactionObserver.h"

@class NSString, SBAppSwitcherSettings, SBAssistantController, SBMainWorkspaceTransaction, UIView, UIViewController, UIWindow;

@interface SBModalUIFluidDismissGestureWorkspaceTransaction : SBSystemGestureWorkspaceTransaction <BSTransactionObserver>
{
    SBAppSwitcherSettings *_settings;
    UIWindow *_gestureWindow;
    UIViewController *_gestureRootViewController;
    UIViewController *_originalParentViewController;
    UIViewController *_dismissingViewController;
    UIView *_viewToAnimate;
    struct CGPoint _dismissingViewTouchOffset;
    struct CGRect _originalBounds;
    struct CGPoint _originalCenter;
    SBAssistantController *_assistantController;
    long long _dismissalType;
    SBMainWorkspaceTransaction *_currentTransaction;
}

@property(retain, nonatomic) SBMainWorkspaceTransaction *currentTransaction; // @synthesize currentTransaction=_currentTransaction;
@property(readonly, nonatomic) long long dismissalType; // @synthesize dismissalType=_dismissalType;
@property(retain, nonatomic) SBAssistantController *assistantController; // @synthesize assistantController=_assistantController;
- (void).cxx_destruct;
- (void)_cleanupHierarchyForDismissal:(_Bool)arg1;
- (void)_addTransactionForDeactivatingAlert;
- (struct CGRect)_containerViewBounds;
- (id)_containerView;
- (double)_swipeUpGestureProgressToDismissedScale;
- (double)_swipeUpTotalYDistanceToDismissedScale;
- (double)_centerYOffsetWhenDismissed;
- (double)_swipeUpGestureTranslation;
- (struct CGRect)_frameForGestureProgress;
- (double)_scaleForGestureProgress;
- (void)_updateDismissingViewLayoutAndStyleForGesture;
- (void)transactionDidComplete:(id)arg1;
- (void)_finishWithGesture:(id)arg1;
- (void)_updateWithGesture:(id)arg1;
- (void)_beginWithGesture:(id)arg1;
- (void)_finishWithCompletionType:(long long)arg1;
- (void)systemGestureStateChanged:(id)arg1;
- (_Bool)_canBeInterrupted;
- (void)_begin;
- (void)_didInterruptWithReason:(id)arg1;
- (_Bool)canInterruptForTransitionRequest:(id)arg1;
- (id)initWithTransitionRequest:(id)arg1 assistantController:(id)arg2 dismissalType:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

