//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPanGestureRecognizer.h"

@interface SBPanSystemGestureRecognizer : UIPanGestureRecognizer
{
    double _touchesBeganTimeInterval;
    _Bool _failsPastMaximumPressDurationWithoutHysteresis;
    double _maximumPressDuration;
}

@property(nonatomic) double maximumPressDuration; // @synthesize maximumPressDuration=_maximumPressDuration;
@property(nonatomic) _Bool failsPastMaximumPressDurationWithoutHysteresis; // @synthesize failsPastMaximumPressDurationWithoutHysteresis=_failsPastMaximumPressDurationWithoutHysteresis;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setState:(long long)arg1;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

// Remaining properties
@property(nonatomic) __weak id <SBSystemGestureRecognizerDelegate> delegate; // @dynamic delegate;

@end

