//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDeckSwitcherPersonality.h"

@interface SBReduceMotionDeckSwitcherPersonality : SBDeckSwitcherPersonality
{
}

- (struct CGSize)contentSize;
- (struct CGPoint)adjustedOffsetForOffset:(struct CGPoint)arg1 translation:(struct CGPoint)arg2 startPoint:(struct CGPoint)arg3 locationInView:(struct CGPoint)arg4 horizontalVelocity:(inout double *)arg5 verticalVelocity:(inout double *)arg6;
- (double)_leadingOffsetForIndex:(unsigned long long)arg1 displayItemsCount:(unsigned long long)arg2 stackedProgress:(double)arg3 scrollProgress:(double)arg4 ignoreInsertionsAndRemovals:(_Bool)arg5;
- (double)_scrollProgressForIndex:(unsigned long long)arg1 displayItemsCount:(unsigned long long)arg2 stackedProgress:(double)arg3 frameOrigin:(double)arg4 ignoreInsertionsAndRemovals:(_Bool)arg5;
- (struct CGRect)_frameForIndex:(unsigned long long)arg1 displayItemsCount:(unsigned long long)arg2 stackedProgress:(double)arg3 scrollProgress:(double)arg4 ignoringScrollOffset:(_Bool)arg5 ignoreInsertionsAndRemovals:(_Bool)arg6;
- (double)_scaleForContainerView;
- (struct CGRect)_frameForContainerView;
- (_Bool)_hideInactiveCardsForAppZoom;
- (double)_titleOpacityForIndex:(unsigned long long)arg1 scrollProgress:(double)arg2;
- (double)titleAndIconOpacityForIndex:(unsigned long long)arg1;
- (double)switcherOpacity;
- (double)wallpaperScale;
- (double)homeScreenScale;
- (struct CGSize)interpageSpacingForPaging;
- (_Bool)scrollViewPagingEnabled;

@end

