//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBSearchEtceteraMetrics : NSObject
{
}

+ (_Bool)_isPortrait;
+ (_Bool)shouldUseMultiLineDateViewForLockScreen;
+ (_Bool)shouldShowDateViewForLockScreen;
+ (double)verticalSpacingBetweenWidgets;
+ (double)defaultRestingOffsetForNavigationBarInset:(double)arg1;
+ (struct UIEdgeInsets)contentInsetsForBounds:(struct CGRect)arg1 contentSize:(struct CGSize)arg2 navigationBarInset:(double)arg3;

@end

