//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBViewControllerTransitionContext, UIViewController;

@protocol SBSpotlightInitiating <NSObject>
@property(retain, nonatomic) SBViewControllerTransitionContext *transitionContext;
- (UIViewController *)spotlightHeaderAcquiringViewController;
- (void)resetForSpotlightDismissalAnimated:(_Bool)arg1;
@end

