//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlert.h"

@class SBSpotlightAlertSpotlightViewController, UIView;

@interface SBSpotlightAlert : SBAlert
{
    CDUnknownBlockType _presentationCompletionHandler;
    SBSpotlightAlertSpotlightViewController *_spotlightViewController;
    UIView *_backgroundView;
}

@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) SBSpotlightAlertSpotlightViewController *spotlightViewController; // @synthesize spotlightViewController=_spotlightViewController;
@property(copy, nonatomic) CDUnknownBlockType presentationCompletionHandler; // @synthesize presentationCompletionHandler=_presentationCompletionHandler;
- (void).cxx_destruct;
- (void)activate;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (_Bool)hasTranslucentBackground;
- (void)orderOutWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)orderFrontWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)alertView;
- (void)loadView;
- (void)viewDidLayoutSubviews;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

