//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CCUIModularControlCenterCardViewControllerDelegate.h"
#import "SBAppSwitcherPageContentView.h"

@class CCUIModularControlCenterCardViewController, NSString, SBControlCenterSystemAgent, SBUIBackgroundView, UIStatusBar;

@interface SBSwitcherControlCenterPageContentView : UIView <CCUIModularControlCenterCardViewControllerDelegate, SBAppSwitcherPageContentView>
{
    _Bool _expandedModuleOpen;
    _Bool _controlCenterActive;
    _Bool _statusBarVisible;
    double _cornerRadius;
    long long _orientation;
    CCUIModularControlCenterCardViewController *_viewController;
    SBControlCenterSystemAgent *_systemAgent;
    SBUIBackgroundView *_backgroundView;
    long long _interactivityMode;
    UIStatusBar *_fakeStatusBar;
}

@property(retain, nonatomic) UIStatusBar *fakeStatusBar; // @synthesize fakeStatusBar=_fakeStatusBar;
@property(nonatomic, getter=isStatusBarVisible) _Bool statusBarVisible; // @synthesize statusBarVisible=_statusBarVisible;
@property(nonatomic, getter=isControlCenterActive) _Bool controlCenterActive; // @synthesize controlCenterActive=_controlCenterActive;
@property(nonatomic) long long interactivityMode; // @synthesize interactivityMode=_interactivityMode;
@property(retain, nonatomic) SBUIBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) SBControlCenterSystemAgent *systemAgent; // @synthesize systemAgent=_systemAgent;
@property(retain, nonatomic) CCUIModularControlCenterCardViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic, getter=isExpandedModuleOpen) _Bool expandedModuleOpen; // @synthesize expandedModuleOpen=_expandedModuleOpen;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
- (void).cxx_destruct;
- (long long)interfaceOrientationForControlCenterViewController:(id)arg1;
- (void)didCloseExpandedModuleForControlCenterViewController:(id)arg1;
- (void)willOpenExpandedModuleForControlCenterViewController:(id)arg1;
- (void)viewDismissing:(id)arg1 forTransitionRequest:(id)arg2;
- (void)viewPresenting:(id)arg1 forTransitionRequest:(id)arg2;
- (void)transitionDidEnd:(_Bool)arg1 forPresentation:(_Bool)arg2 transitionRequest:(id)arg3;
- (void)setVisible:(_Bool)arg1;
- (void)invalidate;
- (double)pageContentScaleOverride;
- (struct UIEdgeInsets)contentViewControllerEdgeInsets;
- (id)contentViewControllerRelevantSnapHeightsInOrientation:(long long)arg1;
- (struct CGSize)contentViewControllerPreferredContentSize;
- (void)closeExpandedModule;
- (void)layoutSubviews;
- (id)initWithContainerViewController:(id)arg1 interactivityMode:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

