//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBHomeScreenButton.h"

@class UIView;

@interface SBSwitcherCardCloseBox : SBHomeScreenButton
{
    UIView *_highlightDarkeningView;
}

+ (struct UIEdgeInsets)backgroundInsets;
+ (id)defaultContentImage;
+ (_Bool)useLargeKillButton;
- (void).cxx_destruct;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

