//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIMainScreenAnimationController.h"

@class NSMutableArray, SBAlert, SBAppStatusBarSettingsAssertion, SBSceneLayoutAnimationWrapperView, SBWindowSelfHostWrapper, UIView;

@interface SBUIAnimationLockScreenToAppZoomIn : SBUIMainScreenAnimationController
{
    SBAlert *_fromAlert;
    SBSceneLayoutAnimationWrapperView *_animationWrapperView;
    SBWindowSelfHostWrapper *_pipWindowWrapper;
    UIView *_viewToAnimate;
    NSMutableArray *_entityIdentifiersRequiringHostView;
    _Bool _finishedZooming;
    _Bool _finishedActivating;
    _Bool _finishedCrossfadingToHostView;
    _Bool _finishedNotificationAnimations;
    SBAppStatusBarSettingsAssertion *_hideStatusBarAssertion;
}

- (void).cxx_destruct;
- (void)_maybeReportAnimationFinished;
- (void)_noteHostCrossfadeDidFinish;
- (void)_maybeStartCrossfade;
- (void)_noteNotificationAnimationsDidFinish;
- (void)_finishedZooming;
- (_Bool)isReasonableMomentToInterrupt;
- (void)_cleanupAnimation;
- (id)animationSettings;
- (void)_doAnimation:(CDUnknownBlockType)arg1;
- (void)_startAnimation;
- (double)initialAppViewScale;
- (void)_prepareAnimation;
- (void)_willSetupStartDependencies;
- (void)_evaluateDependencies;
- (void)_application:(id)arg1 processStateDidChange:(id)arg2;
- (void)_sceneHandle:(id)arg1 didUpdateContentState:(long long)arg2;
- (id)_progressDependencies;
- (_Bool)_waitsForActivatingSceneContentAvailableIfNecessary;
- (void)_setHidden:(_Bool)arg1;
- (_Bool)_shouldDismissBanner;
- (void)dealloc;
- (id)initWithTransitionContextProvider:(id)arg1;
- (id)_getTransitionWindow;

@end

