//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBPressPrecedenceArbiter.h"
#import "UIGestureRecognizerDelegate.h"

@class NSHashTable, NSString, SBApplication, SBPressGestureRecognizer, SBPressSequenceObserver, UIGestureRecognizer;

@interface SBVolumeHardwareButton : NSObject <UIGestureRecognizerDelegate, SBPressPrecedenceArbiter>
{
    unsigned long long _volumeUpAggdStartTime;
    unsigned long long _volumeDownAggdStartTime;
    SBApplication *_lastVolumeUpEventRecipient;
    SBApplication *_lastVolumeDownEventRecipient;
    _Bool _isSBWaitingVolumeUpEvent;
    long long _homeButtonType;
    SBPressGestureRecognizer *_volumeButtonsPressGestureRecognizer;
    UIGestureRecognizer *_screenshotGestureRecognizer;
    NSHashTable *_volumePressBandits;
    SBPressSequenceObserver *_volumeIncrementSequenceObserver;
    SBPressSequenceObserver *_volumeDecrementSequenceObserver;
}

@property(readonly, nonatomic) SBPressSequenceObserver *volumeDecrementSequenceObserver; // @synthesize volumeDecrementSequenceObserver=_volumeDecrementSequenceObserver;
@property(readonly, nonatomic) SBPressSequenceObserver *volumeIncrementSequenceObserver; // @synthesize volumeIncrementSequenceObserver=_volumeIncrementSequenceObserver;
@property(nonatomic) __weak NSHashTable *volumePressBandits; // @synthesize volumePressBandits=_volumePressBandits;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)_aggdLogVolumeButtonWithType:(long long)arg1 down:(_Bool)arg2;
- (void)_logVolumeButtonWithType:(long long)arg1 down:(_Bool)arg2;
- (void)_handleVolumeButtonWithType:(long long)arg1 down:(_Bool)arg2;
- (void)buttonDown:(id)arg1;
- (id)preemptablePressGestureRecognizers;
- (void)_sendBanditsVolumeDecreased;
- (void)_sendBanditsVolumeIncreased;
- (void)_createGestureRecognizers;
- (id)initWithScreenshotGestureRecognizer:(id)arg1 homeButtonType:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

