//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@class SBAnimationSettings;

@interface SBWakeAnimationSettings : SBUISettings
{
    double _backlightFadeDuration;
    double _speedMultiplierForWake;
    double _speedMultiplierForLiftToWake;
    double _authenticateColorBrightness;
    double _authenticateDateAlpha;
    SBAnimationSettings *_authenticateWallpaperFilterSettings;
    SBAnimationSettings *_dateWakeSettings;
    SBAnimationSettings *_contentWakeSettings;
    double _awakeBlurRadius;
    double _awakeColorBrightness;
    double _awakeScale;
    double _awakeDateAlpha;
    SBAnimationSettings *_awakeWallpaperFilterSettings;
    SBAnimationSettings *_awakeWallpaperScaleSettings;
    SBAnimationSettings *_dateSleepSettings;
    double _sleepBlurRadius;
    double _sleepColorBrightness;
    double _sleepScale;
    SBAnimationSettings *_sleepWallpaperFilterSettings;
    SBAnimationSettings *_sleepWallpaperScaleSettings;
}

+ (id)settingsControllerModule;
@property(retain, nonatomic) SBAnimationSettings *sleepWallpaperScaleSettings; // @synthesize sleepWallpaperScaleSettings=_sleepWallpaperScaleSettings;
@property(retain, nonatomic) SBAnimationSettings *sleepWallpaperFilterSettings; // @synthesize sleepWallpaperFilterSettings=_sleepWallpaperFilterSettings;
@property(nonatomic) double sleepScale; // @synthesize sleepScale=_sleepScale;
@property(nonatomic) double sleepColorBrightness; // @synthesize sleepColorBrightness=_sleepColorBrightness;
@property(nonatomic) double sleepBlurRadius; // @synthesize sleepBlurRadius=_sleepBlurRadius;
@property(retain, nonatomic) SBAnimationSettings *dateSleepSettings; // @synthesize dateSleepSettings=_dateSleepSettings;
@property(retain, nonatomic) SBAnimationSettings *awakeWallpaperScaleSettings; // @synthesize awakeWallpaperScaleSettings=_awakeWallpaperScaleSettings;
@property(retain, nonatomic) SBAnimationSettings *awakeWallpaperFilterSettings; // @synthesize awakeWallpaperFilterSettings=_awakeWallpaperFilterSettings;
@property(nonatomic) double awakeDateAlpha; // @synthesize awakeDateAlpha=_awakeDateAlpha;
@property(nonatomic) double awakeScale; // @synthesize awakeScale=_awakeScale;
@property(nonatomic) double awakeColorBrightness; // @synthesize awakeColorBrightness=_awakeColorBrightness;
@property(nonatomic) double awakeBlurRadius; // @synthesize awakeBlurRadius=_awakeBlurRadius;
@property(retain, nonatomic) SBAnimationSettings *contentWakeSettings; // @synthesize contentWakeSettings=_contentWakeSettings;
@property(retain, nonatomic) SBAnimationSettings *dateWakeSettings; // @synthesize dateWakeSettings=_dateWakeSettings;
@property(retain, nonatomic) SBAnimationSettings *authenticateWallpaperFilterSettings; // @synthesize authenticateWallpaperFilterSettings=_authenticateWallpaperFilterSettings;
@property(nonatomic) double authenticateDateAlpha; // @synthesize authenticateDateAlpha=_authenticateDateAlpha;
@property(nonatomic) double authenticateColorBrightness; // @synthesize authenticateColorBrightness=_authenticateColorBrightness;
@property(nonatomic) double speedMultiplierForLiftToWake; // @synthesize speedMultiplierForLiftToWake=_speedMultiplierForLiftToWake;
@property(nonatomic) double speedMultiplierForWake; // @synthesize speedMultiplierForWake=_speedMultiplierForWake;
@property(nonatomic) double backlightFadeDuration; // @synthesize backlightFadeDuration=_backlightFadeDuration;
- (void).cxx_destruct;
- (void)setDefaultValues;

@end

